# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ModifyMovieDialogUI.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ModifyMovieDialog(object):
    def setupUi(self, ModifyMovieDialog):
        ModifyMovieDialog.setObjectName("ModifyMovieDialog")
        ModifyMovieDialog.resize(800, 600)
        self.frame = QtWidgets.QFrame(ModifyMovieDialog)
        self.frame.setGeometry(QtCore.QRect(25, 25, 741, 541))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.Modify = QtWidgets.QPushButton(self.frame)
        self.Modify.setGeometry(QtCore.QRect(180, 490, 90, 28))
        font = QtGui.QFont()
        font.setFamily("宋体")
        self.Modify.setFont(font)
        self.Modify.setDefault(True)
        self.Modify.setObjectName("Modify")
        self.Cancel = QtWidgets.QPushButton(self.frame)
        self.Cancel.setGeometry(QtCore.QRect(520, 490, 90, 28))
        font = QtGui.QFont()
        font.setFamily("宋体")
        self.Cancel.setFont(font)
        self.Cancel.setObjectName("Cancel")
        self.Title = QtWidgets.QLabel(self.frame)
        self.Title.setGeometry(QtCore.QRect(300, 20, 120, 30))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(12)
        self.Title.setFont(font)
        self.Title.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Title.setTextFormat(QtCore.Qt.AutoText)
        self.Title.setAlignment(QtCore.Qt.AlignCenter)
        self.Title.setObjectName("Title")
        self.ProductionCompany = QtWidgets.QLineEdit(self.frame)
        self.ProductionCompany.setGeometry(QtCore.QRect(100, 160, 130, 30))
        font = QtGui.QFont()
        font.setFamily("宋体")
        self.ProductionCompany.setFont(font)
        self.ProductionCompany.setObjectName("ProductionCompany")
        self.MovieName = QtWidgets.QLineEdit(self.frame)
        self.MovieName.setGeometry(QtCore.QRect(100, 80, 130, 30))
        font = QtGui.QFont()
        font.setFamily("宋体")
        self.MovieName.setFont(font)
        self.MovieName.setAutoFillBackground(False)
        self.MovieName.setObjectName("MovieName")
        self.Label1 = QtWidgets.QLabel(self.frame)
        self.Label1.setGeometry(QtCore.QRect(20, 80, 70, 30))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(10)
        self.Label1.setFont(font)
        self.Label1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Label1.setTextFormat(QtCore.Qt.AutoText)
        self.Label1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Label1.setObjectName("Label1")
        self.Label2 = QtWidgets.QLabel(self.frame)
        self.Label2.setGeometry(QtCore.QRect(20, 120, 70, 30))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(10)
        self.Label2.setFont(font)
        self.Label2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Label2.setTextFormat(QtCore.Qt.AutoText)
        self.Label2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Label2.setObjectName("Label2")
        self.Label3 = QtWidgets.QLabel(self.frame)
        self.Label3.setGeometry(QtCore.QRect(20, 160, 70, 30))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(10)
        self.Label3.setFont(font)
        self.Label3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Label3.setTextFormat(QtCore.Qt.AutoText)
        self.Label3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Label3.setObjectName("Label3")
        self.ReleaseDate = QtWidgets.QDateEdit(self.frame)
        self.ReleaseDate.setGeometry(QtCore.QRect(100, 120, 130, 30))
        self.ReleaseDate.setObjectName("ReleaseDate")
        self.CastTable = QtWidgets.QTableWidget(self.frame)
        self.CastTable.setGeometry(QtCore.QRect(270, 240, 271, 221))
        self.CastTable.setRowCount(12)
        self.CastTable.setObjectName("CastTable")
        self.CastTable.setColumnCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.CastTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.CastTable.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.CastTable.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.CastTable.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.CastTable.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.CastTable.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.CastTable.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.CastTable.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.CastTable.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.CastTable.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.CastTable.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.CastTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.CastTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.CastTable.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.CastTable.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.CastTable.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.CastTable.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.CastTable.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.CastTable.setItem(2, 1, item)
        self.CastTable.horizontalHeader().setVisible(False)
        self.CastTable.verticalHeader().setVisible(False)
        self.DirectorTable = QtWidgets.QTableWidget(self.frame)
        self.DirectorTable.setGeometry(QtCore.QRect(20, 240, 211, 221))
        self.DirectorTable.setRowCount(12)
        self.DirectorTable.setObjectName("DirectorTable")
        self.DirectorTable.setColumnCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.DirectorTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.DirectorTable.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.DirectorTable.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.DirectorTable.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.DirectorTable.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.DirectorTable.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.DirectorTable.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.DirectorTable.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.DirectorTable.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.DirectorTable.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.DirectorTable.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.DirectorTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.DirectorTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.DirectorTable.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.DirectorTable.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.DirectorTable.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.DirectorTable.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.DirectorTable.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.DirectorTable.setItem(2, 1, item)
        self.DirectorTable.horizontalHeader().setVisible(False)
        self.DirectorTable.verticalHeader().setVisible(False)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.frame)
        self.plainTextEdit.setGeometry(QtCore.QRect(270, 100, 271, 91))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.Labe4 = QtWidgets.QLabel(self.frame)
        self.Labe4.setGeometry(QtCore.QRect(80, 210, 70, 30))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(10)
        self.Labe4.setFont(font)
        self.Labe4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Labe4.setTextFormat(QtCore.Qt.AutoText)
        self.Labe4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Labe4.setObjectName("Labe4")
        self.Labe4_2 = QtWidgets.QLabel(self.frame)
        self.Labe4_2.setGeometry(QtCore.QRect(370, 210, 70, 30))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(10)
        self.Labe4_2.setFont(font)
        self.Labe4_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Labe4_2.setTextFormat(QtCore.Qt.AutoText)
        self.Labe4_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Labe4_2.setObjectName("Labe4_2")
        self.Labe4_3 = QtWidgets.QLabel(self.frame)
        self.Labe4_3.setGeometry(QtCore.QRect(370, 70, 70, 30))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(10)
        self.Labe4_3.setFont(font)
        self.Labe4_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Labe4_3.setTextFormat(QtCore.Qt.AutoText)
        self.Labe4_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Labe4_3.setObjectName("Labe4_3")
        self.Labe4_4 = QtWidgets.QLabel(self.frame)
        self.Labe4_4.setGeometry(QtCore.QRect(610, 70, 70, 30))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(10)
        self.Labe4_4.setFont(font)
        self.Labe4_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Labe4_4.setTextFormat(QtCore.Qt.AutoText)
        self.Labe4_4.setAlignment(QtCore.Qt.AlignCenter)
        self.Labe4_4.setObjectName("Labe4_4")
        self.GenreTable = QtWidgets.QTableWidget(self.frame)
        self.GenreTable.setGeometry(QtCore.QRect(580, 100, 121, 361))
        self.GenreTable.setRowCount(7)
        self.GenreTable.setObjectName("GenreTable")
        self.GenreTable.setColumnCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.GenreTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.GenreTable.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.GenreTable.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.GenreTable.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.GenreTable.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.GenreTable.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.GenreTable.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.GenreTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.GenreTable.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.GenreTable.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.GenreTable.setItem(2, 0, item)
        self.GenreTable.horizontalHeader().setVisible(False)
        self.GenreTable.verticalHeader().setVisible(False)

        self.retranslateUi(ModifyMovieDialog)
        self.Cancel.clicked.connect(ModifyMovieDialog.reject)
        self.Modify.clicked.connect(ModifyMovieDialog.modifyMovie)
        QtCore.QMetaObject.connectSlotsByName(ModifyMovieDialog)
        ModifyMovieDialog.setTabOrder(self.ProductionCompany, self.Modify)
        ModifyMovieDialog.setTabOrder(self.Modify, self.Cancel)

    def retranslateUi(self, ModifyMovieDialog):
        _translate = QtCore.QCoreApplication.translate
        ModifyMovieDialog.setWindowTitle(_translate("ModifyMovieDialog", "修改电影信息"))
        self.Modify.setText(_translate("ModifyMovieDialog", "修改"))
        self.Cancel.setText(_translate("ModifyMovieDialog", "取消"))
        self.Title.setText(_translate("ModifyMovieDialog", "修改电影信息"))
        self.ProductionCompany.setText(_translate("ModifyMovieDialog", "迪士尼"))
        self.MovieName.setText(_translate("ModifyMovieDialog", "疯狂动物城"))
        self.Label1.setText(_translate("ModifyMovieDialog", "电影名称"))
        self.Label2.setText(_translate("ModifyMovieDialog", "上映日期"))
        self.Label3.setText(_translate("ModifyMovieDialog", "制作公司"))
        item = self.CastTable.verticalHeaderItem(0)
        item.setText(_translate("ModifyMovieDialog", "新建行"))
        item = self.CastTable.verticalHeaderItem(1)
        item.setText(_translate("ModifyMovieDialog", "新建行"))
        item = self.CastTable.verticalHeaderItem(2)
        item.setText(_translate("ModifyMovieDialog", "新建行"))
        item = self.CastTable.verticalHeaderItem(3)
        item.setText(_translate("ModifyMovieDialog", "新建行"))
        item = self.CastTable.verticalHeaderItem(4)
        item.setText(_translate("ModifyMovieDialog", "新建行"))
        item = self.CastTable.verticalHeaderItem(5)
        item.setText(_translate("ModifyMovieDialog", "新建行"))
        item = self.CastTable.verticalHeaderItem(6)
        item.setText(_translate("ModifyMovieDialog", "新建行"))
        item = self.CastTable.verticalHeaderItem(7)
        item.setText(_translate("ModifyMovieDialog", "新建行"))
        item = self.CastTable.verticalHeaderItem(8)
        item.setText(_translate("ModifyMovieDialog", "新建行"))
        item = self.CastTable.verticalHeaderItem(9)
        item.setText(_translate("ModifyMovieDialog", "新建行"))
        item = self.CastTable.verticalHeaderItem(10)
        item.setText(_translate("ModifyMovieDialog", "新建行"))
        item = self.CastTable.horizontalHeaderItem(0)
        item.setText(_translate("ModifyMovieDialog", "姓名"))
        item = self.CastTable.horizontalHeaderItem(1)
        item.setText(_translate("ModifyMovieDialog", "角色"))
        __sortingEnabled = self.CastTable.isSortingEnabled()
        self.CastTable.setSortingEnabled(False)
        item = self.CastTable.item(0, 0)
        item.setText(_translate("ModifyMovieDialog", "演员1"))
        item = self.CastTable.item(0, 1)
        item.setText(_translate("ModifyMovieDialog", "角色1"))
        item = self.CastTable.item(1, 0)
        item.setText(_translate("ModifyMovieDialog", "演员2"))
        item = self.CastTable.item(1, 1)
        item.setText(_translate("ModifyMovieDialog", "角色2"))
        item = self.CastTable.item(2, 0)
        item.setText(_translate("ModifyMovieDialog", "演员3"))
        item = self.CastTable.item(2, 1)
        item.setText(_translate("ModifyMovieDialog", "角色3"))
        self.CastTable.setSortingEnabled(__sortingEnabled)
        item = self.DirectorTable.verticalHeaderItem(0)
        item.setText(_translate("ModifyMovieDialog", "新建行"))
        item = self.DirectorTable.verticalHeaderItem(1)
        item.setText(_translate("ModifyMovieDialog", "新建行"))
        item = self.DirectorTable.verticalHeaderItem(2)
        item.setText(_translate("ModifyMovieDialog", "新建行"))
        item = self.DirectorTable.verticalHeaderItem(3)
        item.setText(_translate("ModifyMovieDialog", "新建行"))
        item = self.DirectorTable.verticalHeaderItem(4)
        item.setText(_translate("ModifyMovieDialog", "新建行"))
        item = self.DirectorTable.verticalHeaderItem(5)
        item.setText(_translate("ModifyMovieDialog", "新建行"))
        item = self.DirectorTable.verticalHeaderItem(6)
        item.setText(_translate("ModifyMovieDialog", "新建行"))
        item = self.DirectorTable.verticalHeaderItem(7)
        item.setText(_translate("ModifyMovieDialog", "新建行"))
        item = self.DirectorTable.verticalHeaderItem(8)
        item.setText(_translate("ModifyMovieDialog", "新建行"))
        item = self.DirectorTable.verticalHeaderItem(9)
        item.setText(_translate("ModifyMovieDialog", "新建行"))
        item = self.DirectorTable.verticalHeaderItem(10)
        item.setText(_translate("ModifyMovieDialog", "新建行"))
        item = self.DirectorTable.horizontalHeaderItem(0)
        item.setText(_translate("ModifyMovieDialog", "姓名"))
        item = self.DirectorTable.horizontalHeaderItem(1)
        item.setText(_translate("ModifyMovieDialog", "执导/编剧"))
        __sortingEnabled = self.DirectorTable.isSortingEnabled()
        self.DirectorTable.setSortingEnabled(False)
        item = self.DirectorTable.item(0, 0)
        item.setText(_translate("ModifyMovieDialog", "导演1"))
        item = self.DirectorTable.item(0, 1)
        item.setText(_translate("ModifyMovieDialog", "执导"))
        item = self.DirectorTable.item(1, 0)
        item.setText(_translate("ModifyMovieDialog", "导演2"))
        item = self.DirectorTable.item(1, 1)
        item.setText(_translate("ModifyMovieDialog", "执导"))
        item = self.DirectorTable.item(2, 0)
        item.setText(_translate("ModifyMovieDialog", "导演3"))
        item = self.DirectorTable.item(2, 1)
        item.setText(_translate("ModifyMovieDialog", "执导"))
        self.DirectorTable.setSortingEnabled(__sortingEnabled)
        self.plainTextEdit.setPlainText(_translate("ModifyMovieDialog", "这是简介这是简介这是简介这是简介这是简介这是简介这是简介这是简介这是简介这是简介这是简介这是简介这是简介这是简介这是简介这是简介这是简介这是简介这是简介这是简介"))
        self.Labe4.setText(_translate("ModifyMovieDialog", "导演信息"))
        self.Labe4_2.setText(_translate("ModifyMovieDialog", "演员信息"))
        self.Labe4_3.setText(_translate("ModifyMovieDialog", "电影简介"))
        self.Labe4_4.setText(_translate("ModifyMovieDialog", "分类"))
        item = self.GenreTable.verticalHeaderItem(0)
        item.setText(_translate("ModifyMovieDialog", "新建行"))
        item = self.GenreTable.verticalHeaderItem(1)
        item.setText(_translate("ModifyMovieDialog", "新建行"))
        item = self.GenreTable.verticalHeaderItem(2)
        item.setText(_translate("ModifyMovieDialog", "新建行"))
        item = self.GenreTable.verticalHeaderItem(3)
        item.setText(_translate("ModifyMovieDialog", "新建行"))
        item = self.GenreTable.verticalHeaderItem(4)
        item.setText(_translate("ModifyMovieDialog", "新建行"))
        item = self.GenreTable.verticalHeaderItem(5)
        item.setText(_translate("ModifyMovieDialog", "新建行"))
        item = self.GenreTable.verticalHeaderItem(6)
        item.setText(_translate("ModifyMovieDialog", "新建行"))
        item = self.GenreTable.horizontalHeaderItem(0)
        item.setText(_translate("ModifyMovieDialog", "新建列"))
        __sortingEnabled = self.GenreTable.isSortingEnabled()
        self.GenreTable.setSortingEnabled(False)
        item = self.GenreTable.item(0, 0)
        item.setText(_translate("ModifyMovieDialog", "类别1"))
        item = self.GenreTable.item(1, 0)
        item.setText(_translate("ModifyMovieDialog", "类别2"))
        item = self.GenreTable.item(2, 0)
        item.setText(_translate("ModifyMovieDialog", "类别3"))
        self.GenreTable.setSortingEnabled(__sortingEnabled)
