# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AllDirectorDialogUI.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AllDirectorDialog(object):
    def setupUi(self, AllDirectorDialog):
        AllDirectorDialog.setObjectName("AllDirectorDialog")
        AllDirectorDialog.resize(640, 480)
        self.tableWidget = QtWidgets.QTableWidget(AllDirectorDialog)
        self.tableWidget.setGeometry(QtCore.QRect(0, 0, 640, 400))
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(16)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(11, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(12, 0, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.ReturnButton = QtWidgets.QPushButton(AllDirectorDialog)
        self.ReturnButton.setGeometry(QtCore.QRect(270, 430, 93, 28))
        self.ReturnButton.setObjectName("ReturnButton")

        self.retranslateUi(AllDirectorDialog)
        self.ReturnButton.clicked.connect(AllDirectorDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(AllDirectorDialog)

    def retranslateUi(self, AllDirectorDialog):
        _translate = QtCore.QCoreApplication.translate
        AllDirectorDialog.setWindowTitle(_translate("AllDirectorDialog", "所有导演"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("AllDirectorDialog", "1"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("AllDirectorDialog", "新建行"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("AllDirectorDialog", "新建行"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("AllDirectorDialog", "新建行"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("AllDirectorDialog", "新建行"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("AllDirectorDialog", "新建行"))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("AllDirectorDialog", "新建行"))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("AllDirectorDialog", "新建行"))
        item = self.tableWidget.verticalHeaderItem(8)
        item.setText(_translate("AllDirectorDialog", "新建行"))
        item = self.tableWidget.verticalHeaderItem(9)
        item.setText(_translate("AllDirectorDialog", "新建行"))
        item = self.tableWidget.verticalHeaderItem(10)
        item.setText(_translate("AllDirectorDialog", "新建行"))
        item = self.tableWidget.verticalHeaderItem(11)
        item.setText(_translate("AllDirectorDialog", "新建行"))
        item = self.tableWidget.verticalHeaderItem(12)
        item.setText(_translate("AllDirectorDialog", "新建行"))
        item = self.tableWidget.verticalHeaderItem(13)
        item.setText(_translate("AllDirectorDialog", "新建行"))
        item = self.tableWidget.verticalHeaderItem(14)
        item.setText(_translate("AllDirectorDialog", "新建行"))
        item = self.tableWidget.verticalHeaderItem(15)
        item.setText(_translate("AllDirectorDialog", "新建行"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("AllDirectorDialog", "姓名"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("AllDirectorDialog", "照片"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("AllDirectorDialog", "导演/编剧"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("AllDirectorDialog", "豆瓣链接"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(11, 0)
        item.setText(_translate("AllDirectorDialog", "A"))
        item = self.tableWidget.item(12, 0)
        item.setText(_translate("AllDirectorDialog", "B"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.ReturnButton.setText(_translate("AllDirectorDialog", "返回"))
