# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ChangeInformationDialogUI.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ChangeInformationDialog(object):
    def setupUi(self, ChangeInformationDialog):
        ChangeInformationDialog.setObjectName("ChangeInformationDialog")
        ChangeInformationDialog.resize(300, 400)
        self.frame = QtWidgets.QFrame(ChangeInformationDialog)
        self.frame.setGeometry(QtCore.QRect(25, 25, 250, 350))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.Modify = QtWidgets.QPushButton(self.frame)
        self.Modify.setGeometry(QtCore.QRect(25, 230, 90, 28))
        font = QtGui.QFont()
        font.setFamily("宋体")
        self.Modify.setFont(font)
        self.Modify.setDefault(True)
        self.Modify.setObjectName("Modify")
        self.Cancel = QtWidgets.QPushButton(self.frame)
        self.Cancel.setGeometry(QtCore.QRect(135, 230, 90, 28))
        font = QtGui.QFont()
        font.setFamily("宋体")
        self.Cancel.setFont(font)
        self.Cancel.setObjectName("Cancel")
        self.Title = QtWidgets.QLabel(self.frame)
        self.Title.setGeometry(QtCore.QRect(65, 30, 120, 30))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(12)
        self.Title.setFont(font)
        self.Title.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Title.setTextFormat(QtCore.Qt.AutoText)
        self.Title.setAlignment(QtCore.Qt.AlignCenter)
        self.Title.setObjectName("Title")
        self.Sex = QtWidgets.QLineEdit(self.frame)
        self.Sex.setGeometry(QtCore.QRect(100, 160, 130, 30))
        font = QtGui.QFont()
        font.setFamily("宋体")
        self.Sex.setFont(font)
        self.Sex.setObjectName("Sex")
        self.Age = QtWidgets.QLineEdit(self.frame)
        self.Age.setGeometry(QtCore.QRect(100, 120, 130, 30))
        font = QtGui.QFont()
        font.setFamily("宋体")
        self.Age.setFont(font)
        self.Age.setAutoFillBackground(False)
        self.Age.setObjectName("Age")
        self.UserName = QtWidgets.QLineEdit(self.frame)
        self.UserName.setGeometry(QtCore.QRect(100, 80, 130, 30))
        font = QtGui.QFont()
        font.setFamily("宋体")
        self.UserName.setFont(font)
        self.UserName.setAutoFillBackground(False)
        self.UserName.setObjectName("UserName")
        self.Label1 = QtWidgets.QLabel(self.frame)
        self.Label1.setGeometry(QtCore.QRect(20, 80, 70, 30))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(10)
        self.Label1.setFont(font)
        self.Label1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Label1.setTextFormat(QtCore.Qt.AutoText)
        self.Label1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Label1.setObjectName("Label1")
        self.Label2 = QtWidgets.QLabel(self.frame)
        self.Label2.setGeometry(QtCore.QRect(20, 120, 70, 30))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(10)
        self.Label2.setFont(font)
        self.Label2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Label2.setTextFormat(QtCore.Qt.AutoText)
        self.Label2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Label2.setObjectName("Label2")
        self.Label3 = QtWidgets.QLabel(self.frame)
        self.Label3.setGeometry(QtCore.QRect(20, 160, 70, 30))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(10)
        self.Label3.setFont(font)
        self.Label3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Label3.setTextFormat(QtCore.Qt.AutoText)
        self.Label3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Label3.setObjectName("Label3")

        self.retranslateUi(ChangeInformationDialog)
        self.Cancel.clicked.connect(ChangeInformationDialog.reject)
        self.Modify.clicked.connect(ChangeInformationDialog.changeInformation)
        QtCore.QMetaObject.connectSlotsByName(ChangeInformationDialog)
        ChangeInformationDialog.setTabOrder(self.Age, self.Sex)
        ChangeInformationDialog.setTabOrder(self.Sex, self.Modify)
        ChangeInformationDialog.setTabOrder(self.Modify, self.Cancel)

    def retranslateUi(self, ChangeInformationDialog):
        _translate = QtCore.QCoreApplication.translate
        ChangeInformationDialog.setWindowTitle(_translate("ChangeInformationDialog", "ChangePassword"))
        self.Modify.setText(_translate("ChangeInformationDialog", "修改"))
        self.Cancel.setText(_translate("ChangeInformationDialog", "取消"))
        self.Title.setText(_translate("ChangeInformationDialog", "修改个人信息"))
        self.Sex.setText(_translate("ChangeInformationDialog", "确认新密码"))
        self.Age.setText(_translate("ChangeInformationDialog", "20"))
        self.UserName.setText(_translate("ChangeInformationDialog", "用户名"))
        self.Label1.setText(_translate("ChangeInformationDialog", "用户名"))
        self.Label2.setText(_translate("ChangeInformationDialog", "年龄"))
        self.Label3.setText(_translate("ChangeInformationDialog", "性别"))
