# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DBProj\GUI\CommentWidgetUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CommentWidget(object):
    def setupUi(self, CommentWidget):
        CommentWidget.setObjectName("CommentWidget")
        CommentWidget.resize(630, 130)
        self.NameLabel = QtWidgets.QLabel(CommentWidget)
        self.NameLabel.setGeometry(QtCore.QRect(10, 10, 480, 30))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.NameLabel.setFont(font)
        self.NameLabel.setObjectName("NameLabel")
        self.RateLabel = QtWidgets.QLabel(CommentWidget)
        self.RateLabel.setGeometry(QtCore.QRect(450, 10, 141, 30))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.RateLabel.setFont(font)
        self.RateLabel.setObjectName("RateLabel")
        self.CommentText = QtWidgets.QTextBrowser(CommentWidget)
        self.CommentText.setGeometry(QtCore.QRect(10, 40, 580, 80))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(38, 107, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(38, 107, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.CommentText.setPalette(palette)
        self.CommentText.setAutoFillBackground(False)
        self.CommentText.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.CommentText.setAcceptRichText(False)
        self.CommentText.setObjectName("CommentText")

        self.retranslateUi(CommentWidget)
        QtCore.QMetaObject.connectSlotsByName(CommentWidget)

    def retranslateUi(self, CommentWidget):
        _translate = QtCore.QCoreApplication.translate
        CommentWidget.setWindowTitle(_translate("CommentWidget", "Form"))
        self.NameLabel.setText(_translate("CommentWidget", "用户昵称"))
        self.RateLabel.setText(_translate("CommentWidget", "评分："))
