# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GuestMainWindowUI.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GuestMainWindow(object):
    def setupUi(self, GuestMainWindow):
        GuestMainWindow.setObjectName("GuestMainWindow")
        GuestMainWindow.resize(960, 640)
        GuestMainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.centralwidget = QtWidgets.QWidget(GuestMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.LoginOrRegister = QtWidgets.QPushButton(self.centralwidget)
        self.LoginOrRegister.setGeometry(QtCore.QRect(65, 340, 120, 30))
        self.LoginOrRegister.setAutoDefault(False)
        self.LoginOrRegister.setDefault(False)
        self.LoginOrRegister.setObjectName("LoginOrRegister")
        self.GuestLabel = QtWidgets.QLabel(self.centralwidget)
        self.GuestLabel.setGeometry(QtCore.QRect(65, 140, 130, 40))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.GuestLabel.setFont(font)
        self.GuestLabel.setScaledContents(False)
        self.GuestLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.GuestLabel.setObjectName("GuestLabel")
        self.VLine = QtWidgets.QFrame(self.centralwidget)
        self.VLine.setGeometry(QtCore.QRect(240, 0, 20, 640))
        self.VLine.setFrameShadow(QtWidgets.QFrame.Plain)
        self.VLine.setLineWidth(3)
        self.VLine.setFrameShape(QtWidgets.QFrame.VLine)
        self.VLine.setObjectName("VLine")
        self.SearchInput = QtWidgets.QLineEdit(self.centralwidget)
        self.SearchInput.setGeometry(QtCore.QRect(350, 90, 425, 30))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.SearchInput.setFont(font)
        self.SearchInput.setObjectName("SearchInput")
        self.Search = QtWidgets.QPushButton(self.centralwidget)
        self.Search.setGeometry(QtCore.QRect(774, 89, 75, 32))
        self.Search.setAutoDefault(True)
        self.Search.setDefault(True)
        self.Search.setObjectName("Search")
        self.HLine = QtWidgets.QFrame(self.centralwidget)
        self.HLine.setGeometry(QtCore.QRect(250, 180, 710, 20))
        self.HLine.setFrameShadow(QtWidgets.QFrame.Plain)
        self.HLine.setFrameShape(QtWidgets.QFrame.HLine)
        self.HLine.setObjectName("HLine")
        self.RecommendationLabel = QtWidgets.QLabel(self.centralwidget)
        self.RecommendationLabel.setGeometry(QtCore.QRect(300, 220, 120, 30))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        self.RecommendationLabel.setFont(font)
        self.RecommendationLabel.setObjectName("RecommendationLabel")
        self.RecommendationPic1 = QtWidgets.QLabel(self.centralwidget)
        self.RecommendationPic1.setGeometry(QtCore.QRect(300, 280, 180, 254))
        self.RecommendationPic1.setText("")
        self.RecommendationPic1.setPixmap(QtGui.QPixmap("C:/Users/12600/Desktop/zootopia.jpg"))
        self.RecommendationPic1.setScaledContents(True)
        self.RecommendationPic1.setObjectName("RecommendationPic1")
        self.RecommendationPic2 = QtWidgets.QLabel(self.centralwidget)
        self.RecommendationPic2.setGeometry(QtCore.QRect(530, 280, 180, 254))
        self.RecommendationPic2.setText("")
        self.RecommendationPic2.setPixmap(QtGui.QPixmap("C:/Users/12600/Desktop/zootopia.jpg"))
        self.RecommendationPic2.setScaledContents(True)
        self.RecommendationPic2.setObjectName("RecommendationPic2")
        self.RecommendationPic3 = QtWidgets.QLabel(self.centralwidget)
        self.RecommendationPic3.setGeometry(QtCore.QRect(760, 280, 180, 254))
        self.RecommendationPic3.setText("")
        self.RecommendationPic3.setPixmap(QtGui.QPixmap("C:/Users/12600/Desktop/zootopia.jpg"))
        self.RecommendationPic3.setScaledContents(True)
        self.RecommendationPic3.setObjectName("RecommendationPic3")
        self.RecommendationTitle1 = QtWidgets.QPushButton(self.centralwidget)
        self.RecommendationTitle1.setGeometry(QtCore.QRect(300, 550, 180, 30))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.RecommendationTitle1.setFont(font)
        self.RecommendationTitle1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.RecommendationTitle1.setStyleSheet("background: transparent")
        self.RecommendationTitle1.setDefault(False)
        self.RecommendationTitle1.setFlat(True)
        self.RecommendationTitle1.setObjectName("RecommendationTitle1")
        self.RecommendationTitle2 = QtWidgets.QPushButton(self.centralwidget)
        self.RecommendationTitle2.setGeometry(QtCore.QRect(530, 550, 180, 30))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.RecommendationTitle2.setFont(font)
        self.RecommendationTitle2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.RecommendationTitle2.setStyleSheet("background: transparent")
        self.RecommendationTitle2.setDefault(False)
        self.RecommendationTitle2.setFlat(True)
        self.RecommendationTitle2.setObjectName("RecommendationTitle2")
        self.RecommendationTitle3 = QtWidgets.QPushButton(self.centralwidget)
        self.RecommendationTitle3.setGeometry(QtCore.QRect(760, 550, 180, 30))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.RecommendationTitle3.setFont(font)
        self.RecommendationTitle3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.RecommendationTitle3.setStyleSheet("background: transparent")
        self.RecommendationTitle3.setDefault(False)
        self.RecommendationTitle3.setFlat(True)
        self.RecommendationTitle3.setObjectName("RecommendationTitle3")
        self.Quit = QtWidgets.QPushButton(self.centralwidget)
        self.Quit.setGeometry(QtCore.QRect(65, 390, 120, 30))
        self.Quit.setObjectName("Quit")
        GuestMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(GuestMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 960, 26))
        self.menubar.setObjectName("menubar")
        GuestMainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(GuestMainWindow)
        self.statusbar.setObjectName("statusbar")
        GuestMainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(GuestMainWindow)
        self.Quit.clicked.connect(GuestMainWindow.close)
        self.RecommendationTitle1.clicked.connect(GuestMainWindow.movie1)
        self.RecommendationTitle2.clicked.connect(GuestMainWindow.movie2)
        self.RecommendationTitle3.clicked.connect(GuestMainWindow.movie3)
        self.LoginOrRegister.clicked.connect(GuestMainWindow.loginOrRegister)
        self.Search.clicked.connect(GuestMainWindow.search)
        QtCore.QMetaObject.connectSlotsByName(GuestMainWindow)
        GuestMainWindow.setTabOrder(self.LoginOrRegister, self.Quit)
        GuestMainWindow.setTabOrder(self.Quit, self.SearchInput)
        GuestMainWindow.setTabOrder(self.SearchInput, self.Search)
        GuestMainWindow.setTabOrder(self.Search, self.RecommendationTitle1)
        GuestMainWindow.setTabOrder(self.RecommendationTitle1, self.RecommendationTitle2)
        GuestMainWindow.setTabOrder(self.RecommendationTitle2, self.RecommendationTitle3)

    def retranslateUi(self, GuestMainWindow):
        _translate = QtCore.QCoreApplication.translate
        GuestMainWindow.setWindowTitle(_translate("GuestMainWindow", "MainWindow"))
        self.LoginOrRegister.setText(_translate("GuestMainWindow", "登录/注册"))
        self.GuestLabel.setText(_translate("GuestMainWindow", "当前未登录"))
        self.SearchInput.setText(_translate("GuestMainWindow", "请输入您想搜索的影片"))
        self.Search.setText(_translate("GuestMainWindow", "搜索"))
        self.RecommendationLabel.setText(_translate("GuestMainWindow", "今日推荐"))
        self.RecommendationTitle1.setText(_translate("GuestMainWindow", "疯狂动物城"))
        self.RecommendationTitle2.setText(_translate("GuestMainWindow", "疯狂动物城"))
        self.RecommendationTitle3.setText(_translate("GuestMainWindow", "疯狂动物城"))
        self.Quit.setText(_translate("GuestMainWindow", "退出系统"))
