# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\DBProj\GUI\HomepagePartUI.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HomepagePart(object):
    def setupUi(self, HomepagePart):
        HomepagePart.setObjectName("HomepagePart")
        HomepagePart.resize(960, 640)
        self.HLineSearch = QtWidgets.QFrame(HomepagePart)
        self.HLineSearch.setGeometry(QtCore.QRect(250, 180, 710, 20))
        self.HLineSearch.setFrameShadow(QtWidgets.QFrame.Plain)
        self.HLineSearch.setFrameShape(QtWidgets.QFrame.HLine)
        self.HLineSearch.setObjectName("HLineSearch")
        self.RecommendationFrame = QtWidgets.QFrame(HomepagePart)
        self.RecommendationFrame.setGeometry(QtCore.QRect(260, 210, 691, 411))
        self.RecommendationFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.RecommendationFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.RecommendationFrame.setObjectName("RecommendationFrame")
        self.RecommendationTitle1 = QtWidgets.QPushButton(self.RecommendationFrame)
        self.RecommendationTitle1.setGeometry(QtCore.QRect(20, 350, 180, 30))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.RecommendationTitle1.setFont(font)
        self.RecommendationTitle1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.RecommendationTitle1.setStyleSheet("background: transparent")
        self.RecommendationTitle1.setDefault(False)
        self.RecommendationTitle1.setFlat(True)
        self.RecommendationTitle1.setObjectName("RecommendationTitle1")
        self.RecommendationTitle2 = QtWidgets.QPushButton(self.RecommendationFrame)
        self.RecommendationTitle2.setGeometry(QtCore.QRect(250, 350, 180, 30))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.RecommendationTitle2.setFont(font)
        self.RecommendationTitle2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.RecommendationTitle2.setStyleSheet("background: transparent")
        self.RecommendationTitle2.setDefault(False)
        self.RecommendationTitle2.setFlat(True)
        self.RecommendationTitle2.setObjectName("RecommendationTitle2")
        self.RecommendationTitle3 = QtWidgets.QPushButton(self.RecommendationFrame)
        self.RecommendationTitle3.setGeometry(QtCore.QRect(480, 350, 180, 30))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.RecommendationTitle3.setFont(font)
        self.RecommendationTitle3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.RecommendationTitle3.setStyleSheet("background: transparent")
        self.RecommendationTitle3.setDefault(False)
        self.RecommendationTitle3.setFlat(True)
        self.RecommendationTitle3.setObjectName("RecommendationTitle3")
        self.RecommendationLabel = QtWidgets.QLabel(self.RecommendationFrame)
        self.RecommendationLabel.setGeometry(QtCore.QRect(20, 20, 120, 30))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(18)
        self.RecommendationLabel.setFont(font)
        self.RecommendationLabel.setObjectName("RecommendationLabel")
        self.RecommendationPicture1 = QtWidgets.QLabel(self.RecommendationFrame)
        self.RecommendationPicture1.setGeometry(QtCore.QRect(20, 80, 180, 254))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(12)
        self.RecommendationPicture1.setFont(font)
        self.RecommendationPicture1.setScaledContents(True)
        self.RecommendationPicture1.setAlignment(QtCore.Qt.AlignCenter)
        self.RecommendationPicture1.setObjectName("RecommendationPicture1")
        self.RecommendationPicture2 = QtWidgets.QLabel(self.RecommendationFrame)
        self.RecommendationPicture2.setGeometry(QtCore.QRect(250, 80, 180, 254))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(12)
        self.RecommendationPicture2.setFont(font)
        self.RecommendationPicture2.setScaledContents(True)
        self.RecommendationPicture2.setAlignment(QtCore.Qt.AlignCenter)
        self.RecommendationPicture2.setObjectName("RecommendationPicture2")
        self.RecommendationPicture3 = QtWidgets.QLabel(self.RecommendationFrame)
        self.RecommendationPicture3.setGeometry(QtCore.QRect(480, 80, 180, 254))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(12)
        self.RecommendationPicture3.setFont(font)
        self.RecommendationPicture3.setScaledContents(True)
        self.RecommendationPicture3.setAlignment(QtCore.Qt.AlignCenter)
        self.RecommendationPicture3.setObjectName("RecommendationPicture3")
        self.SearchFrame = QtWidgets.QFrame(HomepagePart)
        self.SearchFrame.setGeometry(QtCore.QRect(320, 60, 570, 80))
        self.SearchFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.SearchFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.SearchFrame.setObjectName("SearchFrame")
        self.SearchInput = QtWidgets.QLineEdit(self.SearchFrame)
        self.SearchInput.setGeometry(QtCore.QRect(30, 20, 425, 30))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.SearchInput.setFont(font)
        self.SearchInput.setObjectName("SearchInput")
        self.Search = QtWidgets.QPushButton(self.SearchFrame)
        self.Search.setGeometry(QtCore.QRect(470, 20, 75, 30))
        self.Search.setAutoDefault(True)
        self.Search.setDefault(True)
        self.Search.setObjectName("Search")

        self.retranslateUi(HomepagePart)
        self.RecommendationTitle2.clicked.connect(HomepagePart.movie2)
        self.RecommendationTitle1.clicked.connect(HomepagePart.movie1)
        self.RecommendationTitle3.clicked.connect(HomepagePart.movie3)
        self.Search.clicked.connect(HomepagePart.search)
        QtCore.QMetaObject.connectSlotsByName(HomepagePart)

    def retranslateUi(self, HomepagePart):
        _translate = QtCore.QCoreApplication.translate
        HomepagePart.setWindowTitle(_translate("HomepagePart", "Homepage"))
        self.RecommendationTitle1.setText(_translate("HomepagePart", "疯狂动物城"))
        self.RecommendationTitle2.setText(_translate("HomepagePart", "疯狂动物城"))
        self.RecommendationTitle3.setText(_translate("HomepagePart", "疯狂动物城"))
        self.RecommendationLabel.setText(_translate("HomepagePart", "今日推荐"))
        self.SearchInput.setPlaceholderText(_translate("HomepagePart", "请输入您想搜索的影片"))
        self.Search.setText(_translate("HomepagePart", "搜索"))
        self.Search.setShortcut(_translate("HomepagePart", "Return"))
