# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ModifyMoreDialogUI.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ModifyMoreDialog(object):
    def setupUi(self, ModifyMoreDialog):
        ModifyMoreDialog.setObjectName("ModifyMoreDialog")
        ModifyMoreDialog.resize(640, 480)
        self.DirectorTable = QtWidgets.QTableWidget(ModifyMoreDialog)
        self.DirectorTable.setGeometry(QtCore.QRect(330, 30, 281, 221))
        self.DirectorTable.setRowCount(12)
        self.DirectorTable.setObjectName("DirectorTable")
        self.DirectorTable.setColumnCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.DirectorTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.DirectorTable.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.DirectorTable.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.DirectorTable.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.DirectorTable.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.DirectorTable.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.DirectorTable.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.DirectorTable.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.DirectorTable.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.DirectorTable.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.DirectorTable.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.DirectorTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.DirectorTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.DirectorTable.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.DirectorTable.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.DirectorTable.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.DirectorTable.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.DirectorTable.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.DirectorTable.setItem(2, 1, item)
        self.DirectorTable.horizontalHeader().setVisible(True)
        self.DirectorTable.verticalHeader().setVisible(False)
        self.CastTable = QtWidgets.QTableWidget(ModifyMoreDialog)
        self.CastTable.setGeometry(QtCore.QRect(30, 30, 281, 221))
        self.CastTable.setRowCount(12)
        self.CastTable.setObjectName("CastTable")
        self.CastTable.setColumnCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.CastTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.CastTable.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.CastTable.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.CastTable.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.CastTable.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.CastTable.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.CastTable.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.CastTable.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.CastTable.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.CastTable.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.CastTable.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.CastTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.CastTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.CastTable.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.CastTable.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.CastTable.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.CastTable.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.CastTable.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.CastTable.setItem(2, 1, item)
        self.CastTable.horizontalHeader().setVisible(True)
        self.CastTable.verticalHeader().setVisible(False)
        self.GenreTable = QtWidgets.QTableWidget(ModifyMoreDialog)
        self.GenreTable.setGeometry(QtCore.QRect(30, 270, 581, 71))
        self.GenreTable.setRowCount(1)
        self.GenreTable.setObjectName("GenreTable")
        self.GenreTable.setColumnCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.GenreTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.GenreTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.GenreTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.GenreTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.GenreTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.GenreTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.GenreTable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.GenreTable.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.GenreTable.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.GenreTable.setItem(0, 2, item)
        self.GenreTable.horizontalHeader().setVisible(False)
        self.GenreTable.verticalHeader().setVisible(True)
        self.Modify = QtWidgets.QPushButton(ModifyMoreDialog)
        self.Modify.setGeometry(QtCore.QRect(160, 390, 90, 28))
        font = QtGui.QFont()
        font.setFamily("宋体")
        self.Modify.setFont(font)
        self.Modify.setDefault(True)
        self.Modify.setObjectName("Modify")
        self.Cancel = QtWidgets.QPushButton(ModifyMoreDialog)
        self.Cancel.setGeometry(QtCore.QRect(410, 390, 90, 28))
        font = QtGui.QFont()
        font.setFamily("宋体")
        self.Cancel.setFont(font)
        self.Cancel.setObjectName("Cancel")

        self.retranslateUi(ModifyMoreDialog)
        self.Modify.clicked.connect(ModifyMoreDialog.modify)
        self.Cancel.clicked.connect(ModifyMoreDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(ModifyMoreDialog)

    def retranslateUi(self, ModifyMoreDialog):
        _translate = QtCore.QCoreApplication.translate
        ModifyMoreDialog.setWindowTitle(_translate("ModifyMoreDialog", "修改信息"))
        item = self.DirectorTable.verticalHeaderItem(0)
        item.setText(_translate("ModifyMoreDialog", "新建行"))
        item = self.DirectorTable.verticalHeaderItem(1)
        item.setText(_translate("ModifyMoreDialog", "新建行"))
        item = self.DirectorTable.verticalHeaderItem(2)
        item.setText(_translate("ModifyMoreDialog", "新建行"))
        item = self.DirectorTable.verticalHeaderItem(3)
        item.setText(_translate("ModifyMoreDialog", "新建行"))
        item = self.DirectorTable.verticalHeaderItem(4)
        item.setText(_translate("ModifyMoreDialog", "新建行"))
        item = self.DirectorTable.verticalHeaderItem(5)
        item.setText(_translate("ModifyMoreDialog", "新建行"))
        item = self.DirectorTable.verticalHeaderItem(6)
        item.setText(_translate("ModifyMoreDialog", "新建行"))
        item = self.DirectorTable.verticalHeaderItem(7)
        item.setText(_translate("ModifyMoreDialog", "新建行"))
        item = self.DirectorTable.verticalHeaderItem(8)
        item.setText(_translate("ModifyMoreDialog", "新建行"))
        item = self.DirectorTable.verticalHeaderItem(9)
        item.setText(_translate("ModifyMoreDialog", "新建行"))
        item = self.DirectorTable.verticalHeaderItem(10)
        item.setText(_translate("ModifyMoreDialog", "新建行"))
        item = self.DirectorTable.horizontalHeaderItem(0)
        item.setText(_translate("ModifyMoreDialog", "姓名"))
        item = self.DirectorTable.horizontalHeaderItem(1)
        item.setText(_translate("ModifyMoreDialog", "执导/编剧"))
        __sortingEnabled = self.DirectorTable.isSortingEnabled()
        self.DirectorTable.setSortingEnabled(False)
        item = self.DirectorTable.item(0, 0)
        item.setText(_translate("ModifyMoreDialog", "导演1"))
        item = self.DirectorTable.item(0, 1)
        item.setText(_translate("ModifyMoreDialog", "执导"))
        item = self.DirectorTable.item(1, 0)
        item.setText(_translate("ModifyMoreDialog", "导演2"))
        item = self.DirectorTable.item(1, 1)
        item.setText(_translate("ModifyMoreDialog", "执导"))
        item = self.DirectorTable.item(2, 0)
        item.setText(_translate("ModifyMoreDialog", "导演3"))
        item = self.DirectorTable.item(2, 1)
        item.setText(_translate("ModifyMoreDialog", "执导"))
        self.DirectorTable.setSortingEnabled(__sortingEnabled)
        item = self.CastTable.verticalHeaderItem(0)
        item.setText(_translate("ModifyMoreDialog", "新建行"))
        item = self.CastTable.verticalHeaderItem(1)
        item.setText(_translate("ModifyMoreDialog", "新建行"))
        item = self.CastTable.verticalHeaderItem(2)
        item.setText(_translate("ModifyMoreDialog", "新建行"))
        item = self.CastTable.verticalHeaderItem(3)
        item.setText(_translate("ModifyMoreDialog", "新建行"))
        item = self.CastTable.verticalHeaderItem(4)
        item.setText(_translate("ModifyMoreDialog", "新建行"))
        item = self.CastTable.verticalHeaderItem(5)
        item.setText(_translate("ModifyMoreDialog", "新建行"))
        item = self.CastTable.verticalHeaderItem(6)
        item.setText(_translate("ModifyMoreDialog", "新建行"))
        item = self.CastTable.verticalHeaderItem(7)
        item.setText(_translate("ModifyMoreDialog", "新建行"))
        item = self.CastTable.verticalHeaderItem(8)
        item.setText(_translate("ModifyMoreDialog", "新建行"))
        item = self.CastTable.verticalHeaderItem(9)
        item.setText(_translate("ModifyMoreDialog", "新建行"))
        item = self.CastTable.verticalHeaderItem(10)
        item.setText(_translate("ModifyMoreDialog", "新建行"))
        item = self.CastTable.horizontalHeaderItem(0)
        item.setText(_translate("ModifyMoreDialog", "姓名"))
        item = self.CastTable.horizontalHeaderItem(1)
        item.setText(_translate("ModifyMoreDialog", "角色"))
        __sortingEnabled = self.CastTable.isSortingEnabled()
        self.CastTable.setSortingEnabled(False)
        item = self.CastTable.item(0, 0)
        item.setText(_translate("ModifyMoreDialog", "演员1"))
        item = self.CastTable.item(0, 1)
        item.setText(_translate("ModifyMoreDialog", "角色1"))
        item = self.CastTable.item(1, 0)
        item.setText(_translate("ModifyMoreDialog", "演员2"))
        item = self.CastTable.item(1, 1)
        item.setText(_translate("ModifyMoreDialog", "角色2"))
        item = self.CastTable.item(2, 0)
        item.setText(_translate("ModifyMoreDialog", "演员3"))
        item = self.CastTable.item(2, 1)
        item.setText(_translate("ModifyMoreDialog", "角色3"))
        self.CastTable.setSortingEnabled(__sortingEnabled)
        item = self.GenreTable.verticalHeaderItem(0)
        item.setText(_translate("ModifyMoreDialog", "分类"))
        item = self.GenreTable.horizontalHeaderItem(0)
        item.setText(_translate("ModifyMoreDialog", "新建列"))
        item = self.GenreTable.horizontalHeaderItem(1)
        item.setText(_translate("ModifyMoreDialog", "新建列"))
        item = self.GenreTable.horizontalHeaderItem(2)
        item.setText(_translate("ModifyMoreDialog", "新建列"))
        item = self.GenreTable.horizontalHeaderItem(3)
        item.setText(_translate("ModifyMoreDialog", "新建列"))
        item = self.GenreTable.horizontalHeaderItem(4)
        item.setText(_translate("ModifyMoreDialog", "新建列"))
        item = self.GenreTable.horizontalHeaderItem(5)
        item.setText(_translate("ModifyMoreDialog", "新建列"))
        __sortingEnabled = self.GenreTable.isSortingEnabled()
        self.GenreTable.setSortingEnabled(False)
        item = self.GenreTable.item(0, 0)
        item.setText(_translate("ModifyMoreDialog", "类别1"))
        item = self.GenreTable.item(0, 1)
        item.setText(_translate("ModifyMoreDialog", "类别2"))
        item = self.GenreTable.item(0, 2)
        item.setText(_translate("ModifyMoreDialog", "类别3"))
        self.GenreTable.setSortingEnabled(__sortingEnabled)
        self.Modify.setText(_translate("ModifyMoreDialog", "修改"))
        self.Cancel.setText(_translate("ModifyMoreDialog", "取消"))
