# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ModifyMovieDialogUI.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ModifyMovieDialog(object):
    def setupUi(self, ModifyMovieDialog):
        ModifyMovieDialog.setObjectName("ModifyMovieDialog")
        ModifyMovieDialog.resize(300, 400)
        self.frame = QtWidgets.QFrame(ModifyMovieDialog)
        self.frame.setGeometry(QtCore.QRect(25, 25, 250, 350))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.Modify = QtWidgets.QPushButton(self.frame)
        self.Modify.setGeometry(QtCore.QRect(25, 230, 90, 28))
        font = QtGui.QFont()
        font.setFamily("宋体")
        self.Modify.setFont(font)
        self.Modify.setDefault(True)
        self.Modify.setObjectName("Modify")
        self.Cancel = QtWidgets.QPushButton(self.frame)
        self.Cancel.setGeometry(QtCore.QRect(135, 230, 90, 28))
        font = QtGui.QFont()
        font.setFamily("宋体")
        self.Cancel.setFont(font)
        self.Cancel.setObjectName("Cancel")
        self.Title = QtWidgets.QLabel(self.frame)
        self.Title.setGeometry(QtCore.QRect(65, 30, 120, 30))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(12)
        self.Title.setFont(font)
        self.Title.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Title.setTextFormat(QtCore.Qt.AutoText)
        self.Title.setAlignment(QtCore.Qt.AlignCenter)
        self.Title.setObjectName("Title")
        self.ProductionCompany = QtWidgets.QLineEdit(self.frame)
        self.ProductionCompany.setGeometry(QtCore.QRect(100, 160, 130, 30))
        font = QtGui.QFont()
        font.setFamily("宋体")
        self.ProductionCompany.setFont(font)
        self.ProductionCompany.setObjectName("ProductionCompany")
        self.MovieName = QtWidgets.QLineEdit(self.frame)
        self.MovieName.setGeometry(QtCore.QRect(100, 80, 130, 30))
        font = QtGui.QFont()
        font.setFamily("宋体")
        self.MovieName.setFont(font)
        self.MovieName.setAutoFillBackground(False)
        self.MovieName.setObjectName("MovieName")
        self.Label1 = QtWidgets.QLabel(self.frame)
        self.Label1.setGeometry(QtCore.QRect(20, 80, 70, 30))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(10)
        self.Label1.setFont(font)
        self.Label1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Label1.setTextFormat(QtCore.Qt.AutoText)
        self.Label1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Label1.setObjectName("Label1")
        self.Label2 = QtWidgets.QLabel(self.frame)
        self.Label2.setGeometry(QtCore.QRect(20, 120, 70, 30))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(10)
        self.Label2.setFont(font)
        self.Label2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Label2.setTextFormat(QtCore.Qt.AutoText)
        self.Label2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Label2.setObjectName("Label2")
        self.Label3 = QtWidgets.QLabel(self.frame)
        self.Label3.setGeometry(QtCore.QRect(20, 160, 70, 30))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(10)
        self.Label3.setFont(font)
        self.Label3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Label3.setTextFormat(QtCore.Qt.AutoText)
        self.Label3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Label3.setObjectName("Label3")
        self.ReleaseDate = QtWidgets.QDateEdit(self.frame)
        self.ReleaseDate.setGeometry(QtCore.QRect(100, 120, 130, 30))
        self.ReleaseDate.setObjectName("ReleaseDate")
        self.More = QtWidgets.QPushButton(self.frame)
        self.More.setGeometry(QtCore.QRect(25, 270, 200, 28))
        font = QtGui.QFont()
        font.setFamily("宋体")
        self.More.setFont(font)
        self.More.setObjectName("More")

        self.retranslateUi(ModifyMovieDialog)
        self.Cancel.clicked.connect(ModifyMovieDialog.reject)
        self.Modify.clicked.connect(ModifyMovieDialog.modifyMovie)
        self.More.clicked.connect(ModifyMovieDialog.modifyMore)
        QtCore.QMetaObject.connectSlotsByName(ModifyMovieDialog)
        ModifyMovieDialog.setTabOrder(self.ProductionCompany, self.Modify)
        ModifyMovieDialog.setTabOrder(self.Modify, self.Cancel)

    def retranslateUi(self, ModifyMovieDialog):
        _translate = QtCore.QCoreApplication.translate
        ModifyMovieDialog.setWindowTitle(_translate("ModifyMovieDialog", "修改电影信息"))
        self.Modify.setText(_translate("ModifyMovieDialog", "修改"))
        self.Cancel.setText(_translate("ModifyMovieDialog", "取消"))
        self.Title.setText(_translate("ModifyMovieDialog", "修改电影信息"))
        self.ProductionCompany.setText(_translate("ModifyMovieDialog", "迪士尼"))
        self.MovieName.setText(_translate("ModifyMovieDialog", "疯狂动物城"))
        self.Label1.setText(_translate("ModifyMovieDialog", "电影名称"))
        self.Label2.setText(_translate("ModifyMovieDialog", "上映日期"))
        self.Label3.setText(_translate("ModifyMovieDialog", "制作公司"))
        self.More.setText(_translate("ModifyMovieDialog", "更多"))
