# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ModifyMovieDialogUI.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ModifyMovieDialog(object):
    def setupUi(self, ModifyMovieDialog):
        ModifyMovieDialog.setObjectName("ModifyMovieDialog")
        ModifyMovieDialog.resize(800, 600)
        self.FirstPageFrame = QtWidgets.QFrame(ModifyMovieDialog)
        self.FirstPageFrame.setGeometry(QtCore.QRect(25, 25, 741, 541))
        self.FirstPageFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.FirstPageFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.FirstPageFrame.setObjectName("FirstPageFrame")
        self.ProductionCompany = QtWidgets.QLineEdit(self.FirstPageFrame)
        self.ProductionCompany.setGeometry(QtCore.QRect(490, 80, 130, 30))
        font = QtGui.QFont()
        font.setFamily("宋体")
        self.ProductionCompany.setFont(font)
        self.ProductionCompany.setObjectName("ProductionCompany")
        self.MovieName = QtWidgets.QLineEdit(self.FirstPageFrame)
        self.MovieName.setGeometry(QtCore.QRect(200, 80, 130, 30))
        font = QtGui.QFont()
        font.setFamily("宋体")
        self.MovieName.setFont(font)
        self.MovieName.setAutoFillBackground(False)
        self.MovieName.setObjectName("MovieName")
        self.Label1 = QtWidgets.QLabel(self.FirstPageFrame)
        self.Label1.setGeometry(QtCore.QRect(120, 80, 70, 30))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(10)
        self.Label1.setFont(font)
        self.Label1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Label1.setTextFormat(QtCore.Qt.AutoText)
        self.Label1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Label1.setObjectName("Label1")
        self.Label2 = QtWidgets.QLabel(self.FirstPageFrame)
        self.Label2.setGeometry(QtCore.QRect(120, 160, 70, 30))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(10)
        self.Label2.setFont(font)
        self.Label2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Label2.setTextFormat(QtCore.Qt.AutoText)
        self.Label2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Label2.setObjectName("Label2")
        self.Label3 = QtWidgets.QLabel(self.FirstPageFrame)
        self.Label3.setGeometry(QtCore.QRect(400, 80, 70, 30))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(10)
        self.Label3.setFont(font)
        self.Label3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Label3.setTextFormat(QtCore.Qt.AutoText)
        self.Label3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Label3.setObjectName("Label3")
        self.ReleaseDate = QtWidgets.QDateEdit(self.FirstPageFrame)
        self.ReleaseDate.setGeometry(QtCore.QRect(200, 160, 130, 30))
        self.ReleaseDate.setObjectName("ReleaseDate")
        self.CastTable = QtWidgets.QTableWidget(self.FirstPageFrame)
        self.CastTable.setGeometry(QtCore.QRect(270, 240, 271, 221))
        self.CastTable.setRowCount(12)
        self.CastTable.setObjectName("CastTable")
        self.CastTable.setColumnCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.CastTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.CastTable.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.CastTable.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.CastTable.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.CastTable.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.CastTable.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.CastTable.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.CastTable.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.CastTable.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.CastTable.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.CastTable.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.CastTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.CastTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.CastTable.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.CastTable.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.CastTable.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.CastTable.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.CastTable.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.CastTable.setItem(2, 1, item)
        self.CastTable.horizontalHeader().setVisible(False)
        self.CastTable.verticalHeader().setVisible(False)
        self.DirectorTable = QtWidgets.QTableWidget(self.FirstPageFrame)
        self.DirectorTable.setGeometry(QtCore.QRect(20, 240, 211, 221))
        self.DirectorTable.setRowCount(12)
        self.DirectorTable.setObjectName("DirectorTable")
        self.DirectorTable.setColumnCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.DirectorTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.DirectorTable.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.DirectorTable.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.DirectorTable.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.DirectorTable.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.DirectorTable.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.DirectorTable.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.DirectorTable.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.DirectorTable.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.DirectorTable.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.DirectorTable.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.DirectorTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.DirectorTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.DirectorTable.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.DirectorTable.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.DirectorTable.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.DirectorTable.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.DirectorTable.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.DirectorTable.setItem(2, 1, item)
        self.DirectorTable.horizontalHeader().setVisible(False)
        self.DirectorTable.verticalHeader().setVisible(False)
        self.Label4 = QtWidgets.QLabel(self.FirstPageFrame)
        self.Label4.setGeometry(QtCore.QRect(80, 210, 70, 30))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(10)
        self.Label4.setFont(font)
        self.Label4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Label4.setTextFormat(QtCore.Qt.AutoText)
        self.Label4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Label4.setObjectName("Label4")
        self.Label5 = QtWidgets.QLabel(self.FirstPageFrame)
        self.Label5.setGeometry(QtCore.QRect(370, 210, 70, 30))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(10)
        self.Label5.setFont(font)
        self.Label5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Label5.setTextFormat(QtCore.Qt.AutoText)
        self.Label5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Label5.setObjectName("Label5")
        self.Label6 = QtWidgets.QLabel(self.FirstPageFrame)
        self.Label6.setGeometry(QtCore.QRect(610, 210, 70, 30))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(10)
        self.Label6.setFont(font)
        self.Label6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Label6.setTextFormat(QtCore.Qt.AutoText)
        self.Label6.setAlignment(QtCore.Qt.AlignCenter)
        self.Label6.setObjectName("Label6")
        self.GenreTable = QtWidgets.QTableWidget(self.FirstPageFrame)
        self.GenreTable.setGeometry(QtCore.QRect(580, 240, 121, 221))
        self.GenreTable.setRowCount(7)
        self.GenreTable.setObjectName("GenreTable")
        self.GenreTable.setColumnCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.GenreTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.GenreTable.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.GenreTable.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.GenreTable.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.GenreTable.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.GenreTable.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.GenreTable.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.GenreTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.GenreTable.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.GenreTable.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.GenreTable.setItem(2, 0, item)
        self.GenreTable.horizontalHeader().setVisible(False)
        self.GenreTable.verticalHeader().setVisible(False)
        self.NextPage = QtWidgets.QPushButton(self.FirstPageFrame)
        self.NextPage.setGeometry(QtCore.QRect(350, 490, 90, 28))
        font = QtGui.QFont()
        font.setFamily("宋体")
        self.NextPage.setFont(font)
        self.NextPage.setObjectName("NextPage")
        self.Label7 = QtWidgets.QLabel(self.FirstPageFrame)
        self.Label7.setGeometry(QtCore.QRect(120, 120, 70, 30))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(10)
        self.Label7.setFont(font)
        self.Label7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Label7.setTextFormat(QtCore.Qt.AutoText)
        self.Label7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Label7.setObjectName("Label7")
        self.Label8 = QtWidgets.QLabel(self.FirstPageFrame)
        self.Label8.setGeometry(QtCore.QRect(400, 120, 70, 30))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(10)
        self.Label8.setFont(font)
        self.Label8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Label8.setTextFormat(QtCore.Qt.AutoText)
        self.Label8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Label8.setObjectName("Label8")
        self.OriginalName = QtWidgets.QLineEdit(self.FirstPageFrame)
        self.OriginalName.setGeometry(QtCore.QRect(200, 120, 130, 30))
        font = QtGui.QFont()
        font.setFamily("宋体")
        self.OriginalName.setFont(font)
        self.OriginalName.setAutoFillBackground(False)
        self.OriginalName.setObjectName("OriginalName")
        self.MovieLength = QtWidgets.QLineEdit(self.FirstPageFrame)
        self.MovieLength.setGeometry(QtCore.QRect(490, 120, 130, 30))
        font = QtGui.QFont()
        font.setFamily("宋体")
        self.MovieLength.setFont(font)
        self.MovieLength.setObjectName("MovieLength")
        self.Label9 = QtWidgets.QLabel(self.FirstPageFrame)
        self.Label9.setGeometry(QtCore.QRect(400, 160, 70, 30))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(10)
        self.Label9.setFont(font)
        self.Label9.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Label9.setTextFormat(QtCore.Qt.AutoText)
        self.Label9.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Label9.setObjectName("Label9")
        self.Picture = QtWidgets.QLineEdit(self.FirstPageFrame)
        self.Picture.setGeometry(QtCore.QRect(490, 160, 130, 30))
        font = QtGui.QFont()
        font.setFamily("宋体")
        self.Picture.setFont(font)
        self.Picture.setObjectName("Picture")
        self.Modify = QtWidgets.QPushButton(ModifyMovieDialog)
        self.Modify.setGeometry(QtCore.QRect(160, 515, 90, 28))
        font = QtGui.QFont()
        font.setFamily("宋体")
        self.Modify.setFont(font)
        self.Modify.setDefault(True)
        self.Modify.setObjectName("Modify")
        self.Cancel = QtWidgets.QPushButton(ModifyMovieDialog)
        self.Cancel.setGeometry(QtCore.QRect(565, 515, 90, 28))
        font = QtGui.QFont()
        font.setFamily("宋体")
        self.Cancel.setFont(font)
        self.Cancel.setObjectName("Cancel")
        self.Title = QtWidgets.QLabel(ModifyMovieDialog)
        self.Title.setGeometry(QtCore.QRect(350, 60, 120, 30))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(12)
        self.Title.setFont(font)
        self.Title.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Title.setTextFormat(QtCore.Qt.AutoText)
        self.Title.setAlignment(QtCore.Qt.AlignCenter)
        self.Title.setObjectName("Title")
        self.SecondPageFrame = QtWidgets.QFrame(ModifyMovieDialog)
        self.SecondPageFrame.setGeometry(QtCore.QRect(25, 25, 741, 541))
        self.SecondPageFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.SecondPageFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.SecondPageFrame.setObjectName("SecondPageFrame")
        self.PreviousPage = QtWidgets.QPushButton(self.SecondPageFrame)
        self.PreviousPage.setGeometry(QtCore.QRect(350, 490, 90, 28))
        font = QtGui.QFont()
        font.setFamily("宋体")
        self.PreviousPage.setFont(font)
        self.PreviousPage.setObjectName("PreviousPage")
        self.Storyline = QtWidgets.QPlainTextEdit(self.SecondPageFrame)
        self.Storyline.setGeometry(QtCore.QRect(40, 90, 671, 131))
        self.Storyline.setObjectName("Storyline")
        self.Label11 = QtWidgets.QLabel(self.SecondPageFrame)
        self.Label11.setGeometry(QtCore.QRect(40, 60, 70, 30))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(10)
        self.Label11.setFont(font)
        self.Label11.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Label11.setTextFormat(QtCore.Qt.AutoText)
        self.Label11.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Label11.setObjectName("Label11")
        self.Label12 = QtWidgets.QLabel(self.SecondPageFrame)
        self.Label12.setGeometry(QtCore.QRect(40, 240, 70, 30))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(10)
        self.Label12.setFont(font)
        self.Label12.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Label12.setTextFormat(QtCore.Qt.AutoText)
        self.Label12.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Label12.setObjectName("Label12")
        self.PrizeHistory = QtWidgets.QPlainTextEdit(self.SecondPageFrame)
        self.PrizeHistory.setGeometry(QtCore.QRect(40, 270, 671, 111))
        self.PrizeHistory.setObjectName("PrizeHistory")
        self.Label13 = QtWidgets.QLabel(self.SecondPageFrame)
        self.Label13.setGeometry(QtCore.QRect(40, 390, 70, 30))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(10)
        self.Label13.setFont(font)
        self.Label13.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Label13.setTextFormat(QtCore.Qt.AutoText)
        self.Label13.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Label13.setObjectName("Label13")
        self.Remark = QtWidgets.QPlainTextEdit(self.SecondPageFrame)
        self.Remark.setGeometry(QtCore.QRect(40, 420, 671, 61))
        self.Remark.setObjectName("Remark")

        self.retranslateUi(ModifyMovieDialog)
        self.NextPage.clicked.connect(ModifyMovieDialog.toNextPage)
        self.PreviousPage.clicked.connect(ModifyMovieDialog.toPreviousPage)
        self.Modify.clicked.connect(ModifyMovieDialog.modifyMovie)
        self.Cancel.clicked.connect(ModifyMovieDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(ModifyMovieDialog)

    def retranslateUi(self, ModifyMovieDialog):
        _translate = QtCore.QCoreApplication.translate
        ModifyMovieDialog.setWindowTitle(_translate("ModifyMovieDialog", "修改电影信息"))
        self.ProductionCompany.setText(_translate("ModifyMovieDialog", "迪士尼"))
        self.MovieName.setText(_translate("ModifyMovieDialog", "疯狂动物城"))
        self.Label1.setText(_translate("ModifyMovieDialog", "电影名称"))
        self.Label2.setText(_translate("ModifyMovieDialog", "上映日期"))
        self.Label3.setText(_translate("ModifyMovieDialog", "制作公司"))
        item = self.CastTable.verticalHeaderItem(0)
        item.setText(_translate("ModifyMovieDialog", "新建行"))
        item = self.CastTable.verticalHeaderItem(1)
        item.setText(_translate("ModifyMovieDialog", "新建行"))
        item = self.CastTable.verticalHeaderItem(2)
        item.setText(_translate("ModifyMovieDialog", "新建行"))
        item = self.CastTable.verticalHeaderItem(3)
        item.setText(_translate("ModifyMovieDialog", "新建行"))
        item = self.CastTable.verticalHeaderItem(4)
        item.setText(_translate("ModifyMovieDialog", "新建行"))
        item = self.CastTable.verticalHeaderItem(5)
        item.setText(_translate("ModifyMovieDialog", "新建行"))
        item = self.CastTable.verticalHeaderItem(6)
        item.setText(_translate("ModifyMovieDialog", "新建行"))
        item = self.CastTable.verticalHeaderItem(7)
        item.setText(_translate("ModifyMovieDialog", "新建行"))
        item = self.CastTable.verticalHeaderItem(8)
        item.setText(_translate("ModifyMovieDialog", "新建行"))
        item = self.CastTable.verticalHeaderItem(9)
        item.setText(_translate("ModifyMovieDialog", "新建行"))
        item = self.CastTable.verticalHeaderItem(10)
        item.setText(_translate("ModifyMovieDialog", "新建行"))
        item = self.CastTable.horizontalHeaderItem(0)
        item.setText(_translate("ModifyMovieDialog", "姓名"))
        item = self.CastTable.horizontalHeaderItem(1)
        item.setText(_translate("ModifyMovieDialog", "角色"))
        __sortingEnabled = self.CastTable.isSortingEnabled()
        self.CastTable.setSortingEnabled(False)
        item = self.CastTable.item(0, 0)
        item.setText(_translate("ModifyMovieDialog", "演员1"))
        item = self.CastTable.item(0, 1)
        item.setText(_translate("ModifyMovieDialog", "角色1"))
        item = self.CastTable.item(1, 0)
        item.setText(_translate("ModifyMovieDialog", "演员2"))
        item = self.CastTable.item(1, 1)
        item.setText(_translate("ModifyMovieDialog", "角色2"))
        item = self.CastTable.item(2, 0)
        item.setText(_translate("ModifyMovieDialog", "演员3"))
        item = self.CastTable.item(2, 1)
        item.setText(_translate("ModifyMovieDialog", "角色3"))
        self.CastTable.setSortingEnabled(__sortingEnabled)
        item = self.DirectorTable.verticalHeaderItem(0)
        item.setText(_translate("ModifyMovieDialog", "新建行"))
        item = self.DirectorTable.verticalHeaderItem(1)
        item.setText(_translate("ModifyMovieDialog", "新建行"))
        item = self.DirectorTable.verticalHeaderItem(2)
        item.setText(_translate("ModifyMovieDialog", "新建行"))
        item = self.DirectorTable.verticalHeaderItem(3)
        item.setText(_translate("ModifyMovieDialog", "新建行"))
        item = self.DirectorTable.verticalHeaderItem(4)
        item.setText(_translate("ModifyMovieDialog", "新建行"))
        item = self.DirectorTable.verticalHeaderItem(5)
        item.setText(_translate("ModifyMovieDialog", "新建行"))
        item = self.DirectorTable.verticalHeaderItem(6)
        item.setText(_translate("ModifyMovieDialog", "新建行"))
        item = self.DirectorTable.verticalHeaderItem(7)
        item.setText(_translate("ModifyMovieDialog", "新建行"))
        item = self.DirectorTable.verticalHeaderItem(8)
        item.setText(_translate("ModifyMovieDialog", "新建行"))
        item = self.DirectorTable.verticalHeaderItem(9)
        item.setText(_translate("ModifyMovieDialog", "新建行"))
        item = self.DirectorTable.verticalHeaderItem(10)
        item.setText(_translate("ModifyMovieDialog", "新建行"))
        item = self.DirectorTable.horizontalHeaderItem(0)
        item.setText(_translate("ModifyMovieDialog", "姓名"))
        item = self.DirectorTable.horizontalHeaderItem(1)
        item.setText(_translate("ModifyMovieDialog", "执导/编剧"))
        __sortingEnabled = self.DirectorTable.isSortingEnabled()
        self.DirectorTable.setSortingEnabled(False)
        item = self.DirectorTable.item(0, 0)
        item.setText(_translate("ModifyMovieDialog", "导演1"))
        item = self.DirectorTable.item(0, 1)
        item.setText(_translate("ModifyMovieDialog", "执导"))
        item = self.DirectorTable.item(1, 0)
        item.setText(_translate("ModifyMovieDialog", "导演2"))
        item = self.DirectorTable.item(1, 1)
        item.setText(_translate("ModifyMovieDialog", "执导"))
        item = self.DirectorTable.item(2, 0)
        item.setText(_translate("ModifyMovieDialog", "导演3"))
        item = self.DirectorTable.item(2, 1)
        item.setText(_translate("ModifyMovieDialog", "执导"))
        self.DirectorTable.setSortingEnabled(__sortingEnabled)
        self.Label4.setText(_translate("ModifyMovieDialog", "导演信息"))
        self.Label5.setText(_translate("ModifyMovieDialog", "演员信息"))
        self.Label6.setText(_translate("ModifyMovieDialog", "分类"))
        item = self.GenreTable.verticalHeaderItem(0)
        item.setText(_translate("ModifyMovieDialog", "新建行"))
        item = self.GenreTable.verticalHeaderItem(1)
        item.setText(_translate("ModifyMovieDialog", "新建行"))
        item = self.GenreTable.verticalHeaderItem(2)
        item.setText(_translate("ModifyMovieDialog", "新建行"))
        item = self.GenreTable.verticalHeaderItem(3)
        item.setText(_translate("ModifyMovieDialog", "新建行"))
        item = self.GenreTable.verticalHeaderItem(4)
        item.setText(_translate("ModifyMovieDialog", "新建行"))
        item = self.GenreTable.verticalHeaderItem(5)
        item.setText(_translate("ModifyMovieDialog", "新建行"))
        item = self.GenreTable.verticalHeaderItem(6)
        item.setText(_translate("ModifyMovieDialog", "新建行"))
        item = self.GenreTable.horizontalHeaderItem(0)
        item.setText(_translate("ModifyMovieDialog", "新建列"))
        __sortingEnabled = self.GenreTable.isSortingEnabled()
        self.GenreTable.setSortingEnabled(False)
        item = self.GenreTable.item(0, 0)
        item.setText(_translate("ModifyMovieDialog", "类别1"))
        item = self.GenreTable.item(1, 0)
        item.setText(_translate("ModifyMovieDialog", "类别2"))
        item = self.GenreTable.item(2, 0)
        item.setText(_translate("ModifyMovieDialog", "类别3"))
        self.GenreTable.setSortingEnabled(__sortingEnabled)
        self.NextPage.setText(_translate("ModifyMovieDialog", "下一页"))
        self.Label7.setText(_translate("ModifyMovieDialog", "电影原名"))
        self.Label8.setText(_translate("ModifyMovieDialog", "电影长度"))
        self.OriginalName.setText(_translate("ModifyMovieDialog", "疯狂动物城"))
        self.MovieLength.setText(_translate("ModifyMovieDialog", "90分钟"))
        self.Label9.setText(_translate("ModifyMovieDialog", "海报链接"))
        self.Picture.setText(_translate("ModifyMovieDialog", "暂无"))
        self.Modify.setText(_translate("ModifyMovieDialog", "修改"))
        self.Cancel.setText(_translate("ModifyMovieDialog", "取消"))
        self.Title.setText(_translate("ModifyMovieDialog", "修改电影信息"))
        self.PreviousPage.setText(_translate("ModifyMovieDialog", "上一页"))
        self.Label11.setText(_translate("ModifyMovieDialog", "电影简介"))
        self.Label12.setText(_translate("ModifyMovieDialog", "获奖信息"))
        self.Label13.setText(_translate("ModifyMovieDialog", "备注"))
