# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SearchResultPartUI.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SearchResultPart(object):
    def setupUi(self, SearchResultPart):
        SearchResultPart.setObjectName("SearchResultPart")
        SearchResultPart.resize(960, 640)
        self.SearchResultFrame = QtWidgets.QFrame(SearchResultPart)
        self.SearchResultFrame.setGeometry(QtCore.QRect(250, 200, 701, 411))
        self.SearchResultFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.SearchResultFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.SearchResultFrame.setObjectName("SearchResultFrame")
        self.tableWidget = QtWidgets.QTableWidget(self.SearchResultFrame)
        self.tableWidget.setGeometry(QtCore.QRect(10, 40, 681, 361))
        self.tableWidget.setRowCount(20)
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("华文琥珀")
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("华文琥珀")
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("华文琥珀")
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("华文琥珀")
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("华文琥珀")
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("华文琥珀")
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("华文琥珀")
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("华文琥珀")
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("华文琥珀")
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 4, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget.horizontalHeader().setStretchLastSection(False)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.SearchResultFrame)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 0, 681, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.DefaultSort = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.DefaultSort.setObjectName("DefaultSort")
        self.horizontalLayout.addWidget(self.DefaultSort)
        self.DateSort = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.DateSort.setObjectName("DateSort")
        self.horizontalLayout.addWidget(self.DateSort)
        self.RateSort = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.RateSort.setObjectName("RateSort")
        self.horizontalLayout.addWidget(self.RateSort)
        self.ReturnRecommendation = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.ReturnRecommendation.setObjectName("ReturnRecommendation")
        self.horizontalLayout.addWidget(self.ReturnRecommendation)

        self.retranslateUi(SearchResultPart)
        self.ReturnRecommendation.clicked.connect(SearchResultPart.returnRecommendation)
        QtCore.QMetaObject.connectSlotsByName(SearchResultPart)

    def retranslateUi(self, SearchResultPart):
        _translate = QtCore.QCoreApplication.translate
        SearchResultPart.setWindowTitle(_translate("SearchResultPart", "搜索结果"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("SearchResultPart", "1"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("SearchResultPart", "2"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("SearchResultPart", "3"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("SearchResultPart", "4"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("SearchResultPart", "5"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("SearchResultPart", "6"))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("SearchResultPart", "7"))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("SearchResultPart", "8"))
        item = self.tableWidget.verticalHeaderItem(8)
        item.setText(_translate("SearchResultPart", "9"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("SearchResultPart", "片名"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("SearchResultPart", "国家"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("SearchResultPart", "上映时间"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("SearchResultPart", "分类"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("SearchResultPart", "评分"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("SearchResultPart", "操作"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("SearchResultPart", "电影1"))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("SearchResultPart", "美国"))
        item = self.tableWidget.item(0, 2)
        item.setText(_translate("SearchResultPart", "2020-6-16"))
        item = self.tableWidget.item(0, 3)
        item.setText(_translate("SearchResultPart", "类别"))
        item = self.tableWidget.item(0, 4)
        item.setText(_translate("SearchResultPart", "5"))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("SearchResultPart", "电影2"))
        item = self.tableWidget.item(1, 1)
        item.setText(_translate("SearchResultPart", "美国"))
        item = self.tableWidget.item(1, 2)
        item.setText(_translate("SearchResultPart", "2020-6-16"))
        item = self.tableWidget.item(1, 3)
        item.setText(_translate("SearchResultPart", "佚名"))
        item = self.tableWidget.item(1, 4)
        item.setText(_translate("SearchResultPart", "4.9"))
        item = self.tableWidget.item(2, 0)
        item.setText(_translate("SearchResultPart", "电影3"))
        item = self.tableWidget.item(2, 1)
        item.setText(_translate("SearchResultPart", "美国"))
        item = self.tableWidget.item(2, 2)
        item.setText(_translate("SearchResultPart", "2020-6-16"))
        item = self.tableWidget.item(2, 3)
        item.setText(_translate("SearchResultPart", "佚名"))
        item = self.tableWidget.item(2, 4)
        item.setText(_translate("SearchResultPart", "4.8"))
        item = self.tableWidget.item(3, 0)
        item.setText(_translate("SearchResultPart", "电影4"))
        item = self.tableWidget.item(3, 1)
        item.setText(_translate("SearchResultPart", "美国"))
        item = self.tableWidget.item(3, 2)
        item.setText(_translate("SearchResultPart", "2020-6-16"))
        item = self.tableWidget.item(3, 3)
        item.setText(_translate("SearchResultPart", "佚名"))
        item = self.tableWidget.item(3, 4)
        item.setText(_translate("SearchResultPart", "4.7"))
        item = self.tableWidget.item(4, 0)
        item.setText(_translate("SearchResultPart", "电影5"))
        item = self.tableWidget.item(4, 1)
        item.setText(_translate("SearchResultPart", "美国"))
        item = self.tableWidget.item(4, 2)
        item.setText(_translate("SearchResultPart", "2020-6-16"))
        item = self.tableWidget.item(4, 3)
        item.setText(_translate("SearchResultPart", "佚名"))
        item = self.tableWidget.item(4, 4)
        item.setText(_translate("SearchResultPart", "4.6"))
        item = self.tableWidget.item(5, 0)
        item.setText(_translate("SearchResultPart", "电影6"))
        item = self.tableWidget.item(5, 1)
        item.setText(_translate("SearchResultPart", "美国"))
        item = self.tableWidget.item(5, 2)
        item.setText(_translate("SearchResultPart", "2020-6-16"))
        item = self.tableWidget.item(5, 3)
        item.setText(_translate("SearchResultPart", "佚名"))
        item = self.tableWidget.item(5, 4)
        item.setText(_translate("SearchResultPart", "4.5"))
        item = self.tableWidget.item(6, 0)
        item.setText(_translate("SearchResultPart", "电影7"))
        item = self.tableWidget.item(6, 1)
        item.setText(_translate("SearchResultPart", "美国"))
        item = self.tableWidget.item(6, 2)
        item.setText(_translate("SearchResultPart", "2020-6-16"))
        item = self.tableWidget.item(6, 3)
        item.setText(_translate("SearchResultPart", "佚名"))
        item = self.tableWidget.item(6, 4)
        item.setText(_translate("SearchResultPart", "4.4"))
        item = self.tableWidget.item(7, 0)
        item.setText(_translate("SearchResultPart", "电影8"))
        item = self.tableWidget.item(7, 1)
        item.setText(_translate("SearchResultPart", "美国"))
        item = self.tableWidget.item(7, 2)
        item.setText(_translate("SearchResultPart", "2020-6-16"))
        item = self.tableWidget.item(7, 3)
        item.setText(_translate("SearchResultPart", "佚名"))
        item = self.tableWidget.item(7, 4)
        item.setText(_translate("SearchResultPart", "4.3"))
        item = self.tableWidget.item(8, 0)
        item.setText(_translate("SearchResultPart", "电影9"))
        item = self.tableWidget.item(8, 1)
        item.setText(_translate("SearchResultPart", "美国"))
        item = self.tableWidget.item(8, 2)
        item.setText(_translate("SearchResultPart", "2020-6-16"))
        item = self.tableWidget.item(8, 3)
        item.setText(_translate("SearchResultPart", "佚名"))
        item = self.tableWidget.item(8, 4)
        item.setText(_translate("SearchResultPart", "4.2"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.DefaultSort.setText(_translate("SearchResultPart", "默认排序"))
        self.DateSort.setText(_translate("SearchResultPart", "按上映时间排序和筛选"))
        self.RateSort.setText(_translate("SearchResultPart", "按评分排序和筛选"))
        self.ReturnRecommendation.setText(_translate("SearchResultPart", "返回首页"))
