# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SearchSettingDialogUI.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SearchSettingDialog(object):
    def setupUi(self, SearchSettingDialog):
        SearchSettingDialog.setObjectName("SearchSettingDialog")
        SearchSettingDialog.resize(480, 360)
        self.Label1 = QtWidgets.QLabel(SearchSettingDialog)
        self.Label1.setGeometry(QtCore.QRect(70, 110, 70, 22))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(10)
        self.Label1.setFont(font)
        self.Label1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Label1.setTextFormat(QtCore.Qt.AutoText)
        self.Label1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Label1.setObjectName("Label1")
        self.Title = QtWidgets.QLabel(SearchSettingDialog)
        self.Title.setGeometry(QtCore.QRect(200, 50, 120, 30))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(12)
        self.Title.setFont(font)
        self.Title.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Title.setTextFormat(QtCore.Qt.AutoText)
        self.Title.setAlignment(QtCore.Qt.AlignCenter)
        self.Title.setObjectName("Title")
        self.RateLow = QtWidgets.QDoubleSpinBox(SearchSettingDialog)
        self.RateLow.setGeometry(QtCore.QRect(150, 110, 110, 22))
        self.RateLow.setDecimals(1)
        self.RateLow.setMaximum(10.0)
        self.RateLow.setObjectName("RateLow")
        self.Label2 = QtWidgets.QLabel(SearchSettingDialog)
        self.Label2.setGeometry(QtCore.QRect(280, 110, 70, 22))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(10)
        self.Label2.setFont(font)
        self.Label2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Label2.setTextFormat(QtCore.Qt.AutoText)
        self.Label2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Label2.setObjectName("Label2")
        self.RateHigh = QtWidgets.QDoubleSpinBox(SearchSettingDialog)
        self.RateHigh.setGeometry(QtCore.QRect(330, 110, 110, 22))
        self.RateHigh.setDecimals(1)
        self.RateHigh.setMaximum(10.0)
        self.RateHigh.setProperty("value", 10.0)
        self.RateHigh.setObjectName("RateHigh")
        self.Label3 = QtWidgets.QLabel(SearchSettingDialog)
        self.Label3.setGeometry(QtCore.QRect(70, 170, 70, 22))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(10)
        self.Label3.setFont(font)
        self.Label3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Label3.setTextFormat(QtCore.Qt.AutoText)
        self.Label3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Label3.setObjectName("Label3")
        self.Label4 = QtWidgets.QLabel(SearchSettingDialog)
        self.Label4.setGeometry(QtCore.QRect(280, 170, 70, 22))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(10)
        self.Label4.setFont(font)
        self.Label4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Label4.setTextFormat(QtCore.Qt.AutoText)
        self.Label4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Label4.setObjectName("Label4")
        self.DateLow = QtWidgets.QDateEdit(SearchSettingDialog)
        self.DateLow.setGeometry(QtCore.QRect(150, 170, 110, 22))
        self.DateLow.setDateTime(QtCore.QDateTime(QtCore.QDate(1900, 1, 1), QtCore.QTime(0, 0, 0)))
        self.DateLow.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(1900, 1, 1), QtCore.QTime(0, 0, 0)))
        self.DateLow.setMaximumDate(QtCore.QDate(2025, 12, 31))
        self.DateLow.setObjectName("DateLow")
        self.Label5 = QtWidgets.QLabel(SearchSettingDialog)
        self.Label5.setGeometry(QtCore.QRect(70, 230, 70, 22))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(10)
        self.Label5.setFont(font)
        self.Label5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Label5.setTextFormat(QtCore.Qt.AutoText)
        self.Label5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Label5.setObjectName("Label5")
        self.Genre2 = QtWidgets.QComboBox(SearchSettingDialog)
        self.Genre2.setGeometry(QtCore.QRect(255, 230, 80, 22))
        self.Genre2.setObjectName("Genre2")
        self.Genre2.addItem("")
        self.Genre2.addItem("")
        self.Genre2.addItem("")
        self.Genre2.addItem("")
        self.Genre2.addItem("")
        self.Genre2.addItem("")
        self.Genre2.addItem("")
        self.Genre2.addItem("")
        self.Genre2.addItem("")
        self.Genre2.addItem("")
        self.Genre2.addItem("")
        self.Genre2.addItem("")
        self.Genre2.addItem("")
        self.Genre2.addItem("")
        self.Genre2.addItem("")
        self.Genre2.addItem("")
        self.Genre2.addItem("")
        self.Genre2.addItem("")
        self.Genre2.addItem("")
        self.Genre2.addItem("")
        self.Genre2.addItem("")
        self.Genre2.addItem("")
        self.Genre2.addItem("")
        self.Genre2.addItem("")
        self.Genre2.addItem("")
        self.Genre2.addItem("")
        self.Genre2.addItem("")
        self.Genre2.addItem("")
        self.Genre2.addItem("")
        self.Genre2.addItem("")
        self.Genre2.addItem("")
        self.Genre2.addItem("")
        self.Genre2.addItem("")
        self.Genre2.addItem("")
        self.Genre2.addItem("")
        self.DateHigh = QtWidgets.QDateEdit(SearchSettingDialog)
        self.DateHigh.setGeometry(QtCore.QRect(330, 170, 110, 22))
        self.DateHigh.setDateTime(QtCore.QDateTime(QtCore.QDate(2025, 12, 31), QtCore.QTime(0, 0, 0)))
        self.DateHigh.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(1900, 1, 1), QtCore.QTime(0, 0, 0)))
        self.DateHigh.setMaximumDate(QtCore.QDate(2025, 12, 31))
        self.DateHigh.setMinimumDate(QtCore.QDate(1900, 1, 1))
        self.DateHigh.setObjectName("DateHigh")
        self.Cancel = QtWidgets.QPushButton(SearchSettingDialog)
        self.Cancel.setGeometry(QtCore.QRect(260, 280, 100, 30))
        font = QtGui.QFont()
        font.setFamily("宋体")
        self.Cancel.setFont(font)
        self.Cancel.setObjectName("Cancel")
        self.Confirm = QtWidgets.QPushButton(SearchSettingDialog)
        self.Confirm.setGeometry(QtCore.QRect(140, 280, 100, 30))
        font = QtGui.QFont()
        font.setFamily("宋体")
        self.Confirm.setFont(font)
        self.Confirm.setDefault(True)
        self.Confirm.setObjectName("Confirm")

        self.retranslateUi(SearchSettingDialog)
        self.Cancel.clicked.connect(SearchSettingDialog.reject)
        self.Confirm.clicked.connect(SearchSettingDialog.setSearch)
        QtCore.QMetaObject.connectSlotsByName(SearchSettingDialog)

    def retranslateUi(self, SearchSettingDialog):
        _translate = QtCore.QCoreApplication.translate
        SearchSettingDialog.setWindowTitle(_translate("SearchSettingDialog", "搜索条件设置"))
        self.Label1.setText(_translate("SearchSettingDialog", "电影评分"))
        self.Title.setText(_translate("SearchSettingDialog", "搜索条件设置"))
        self.Label2.setText(_translate("SearchSettingDialog", "到"))
        self.Label3.setText(_translate("SearchSettingDialog", "上映时间"))
        self.Label4.setText(_translate("SearchSettingDialog", "到"))
        self.Label5.setText(_translate("SearchSettingDialog", "分类"))
        self.Genre2.setItemText(0, _translate("SearchSettingDialog", "不限"))
        self.Genre2.setItemText(1, _translate("SearchSettingDialog", "爱情"))
        self.Genre2.setItemText(2, _translate("SearchSettingDialog", "传记"))
        self.Genre2.setItemText(3, _translate("SearchSettingDialog", "动画"))
        self.Genre2.setItemText(4, _translate("SearchSettingDialog", "动作"))
        self.Genre2.setItemText(5, _translate("SearchSettingDialog", "短片"))
        self.Genre2.setItemText(6, _translate("SearchSettingDialog", "儿童"))
        self.Genre2.setItemText(7, _translate("SearchSettingDialog", "犯罪"))
        self.Genre2.setItemText(8, _translate("SearchSettingDialog", "歌舞"))
        self.Genre2.setItemText(9, _translate("SearchSettingDialog", "古装"))
        self.Genre2.setItemText(10, _translate("SearchSettingDialog", "鬼怪"))
        self.Genre2.setItemText(11, _translate("SearchSettingDialog", "黑色电影"))
        self.Genre2.setItemText(12, _translate("SearchSettingDialog", "荒诞"))
        self.Genre2.setItemText(13, _translate("SearchSettingDialog", "家庭"))
        self.Genre2.setItemText(14, _translate("SearchSettingDialog", "惊悚"))
        self.Genre2.setItemText(15, _translate("SearchSettingDialog", "剧情"))
        self.Genre2.setItemText(16, _translate("SearchSettingDialog", "科幻"))
        self.Genre2.setItemText(17, _translate("SearchSettingDialog", "恐怖"))
        self.Genre2.setItemText(18, _translate("SearchSettingDialog", "历史"))
        self.Genre2.setItemText(19, _translate("SearchSettingDialog", "冒险"))
        self.Genre2.setItemText(20, _translate("SearchSettingDialog", "奇幻"))
        self.Genre2.setItemText(21, _translate("SearchSettingDialog", "情色"))
        self.Genre2.setItemText(22, _translate("SearchSettingDialog", "同性"))
        self.Genre2.setItemText(23, _translate("SearchSettingDialog", "脱口秀"))
        self.Genre2.setItemText(24, _translate("SearchSettingDialog", "武侠"))
        self.Genre2.setItemText(25, _translate("SearchSettingDialog", "舞台艺术"))
        self.Genre2.setItemText(26, _translate("SearchSettingDialog", "西部"))
        self.Genre2.setItemText(27, _translate("SearchSettingDialog", "喜剧"))
        self.Genre2.setItemText(28, _translate("SearchSettingDialog", "戏曲"))
        self.Genre2.setItemText(29, _translate("SearchSettingDialog", "悬疑"))
        self.Genre2.setItemText(30, _translate("SearchSettingDialog", "音乐"))
        self.Genre2.setItemText(31, _translate("SearchSettingDialog", "运动"))
        self.Genre2.setItemText(32, _translate("SearchSettingDialog", "灾难"))
        self.Genre2.setItemText(33, _translate("SearchSettingDialog", "战争"))
        self.Genre2.setItemText(34, _translate("SearchSettingDialog", "真人秀"))
        self.Cancel.setText(_translate("SearchSettingDialog", "取消"))
        self.Confirm.setText(_translate("SearchSettingDialog", "确认"))
