# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DBProj\GUI\SearchResultPartUI.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SearchResultPart(object):
    def setupUi(self, SearchResultPart):
        SearchResultPart.setObjectName("SearchResultPart")
        SearchResultPart.resize(960, 640)
        self.SearchResultFrame = QtWidgets.QFrame(SearchResultPart)
        self.SearchResultFrame.setGeometry(QtCore.QRect(250, 200, 701, 411))
        self.SearchResultFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.SearchResultFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.SearchResultFrame.setObjectName("SearchResultFrame")
        self.tableWidget = QtWidgets.QTableWidget(self.SearchResultFrame)
        self.tableWidget.setGeometry(QtCore.QRect(10, 40, 681, 361))
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(5, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.SearchResultFrame)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 0, 681, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.DefaultSort = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.DefaultSort.setObjectName("DefaultSort")
        self.horizontalLayout.addWidget(self.DefaultSort)
        self.DateSort = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.DateSort.setObjectName("DateSort")
        self.horizontalLayout.addWidget(self.DateSort)
        self.RateSort = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.RateSort.setObjectName("RateSort")
        self.horizontalLayout.addWidget(self.RateSort)
        self.ReturnRecommendation = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.ReturnRecommendation.setObjectName("ReturnRecommendation")
        self.horizontalLayout.addWidget(self.ReturnRecommendation)

        self.retranslateUi(SearchResultPart)
        self.ReturnRecommendation.clicked.connect(SearchResultPart.returnRecommendation)
        QtCore.QMetaObject.connectSlotsByName(SearchResultPart)

    def retranslateUi(self, SearchResultPart):
        _translate = QtCore.QCoreApplication.translate
        SearchResultPart.setWindowTitle(_translate("SearchResultPart", "搜索结果"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("SearchResultPart", "片名"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("SearchResultPart", "国家"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("SearchResultPart", "上映时间"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("SearchResultPart", "分类"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("SearchResultPart", "评分"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("SearchResultPart", "操作"))
        self.DefaultSort.setText(_translate("SearchResultPart", "默认排序"))
        self.DateSort.setText(_translate("SearchResultPart", "按上映时间排序和筛选"))
        self.RateSort.setText(_translate("SearchResultPart", "按评分排序和筛选"))
        self.ReturnRecommendation.setText(_translate("SearchResultPart", "返回首页"))
