# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\DBProj\GUI\SearchSettingDialogUI.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SearchSettingDialog(object):
    def setupUi(self, SearchSettingDialog):
        SearchSettingDialog.setObjectName("SearchSettingDialog")
        SearchSettingDialog.resize(360, 240)
        self.RatingLabel = QtWidgets.QLabel(SearchSettingDialog)
        self.RatingLabel.setGeometry(QtCore.QRect(20, 80, 70, 30))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(12)
        self.RatingLabel.setFont(font)
        self.RatingLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.RatingLabel.setTextFormat(QtCore.Qt.AutoText)
        self.RatingLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.RatingLabel.setObjectName("RatingLabel")
        self.Title = QtWidgets.QLabel(SearchSettingDialog)
        self.Title.setGeometry(QtCore.QRect(100, 30, 160, 30))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.Title.setFont(font)
        self.Title.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Title.setTextFormat(QtCore.Qt.AutoText)
        self.Title.setAlignment(QtCore.Qt.AlignCenter)
        self.Title.setObjectName("Title")
        self.RatingLow = QtWidgets.QDoubleSpinBox(SearchSettingDialog)
        self.RatingLow.setGeometry(QtCore.QRect(100, 80, 100, 30))
        self.RatingLow.setDecimals(1)
        self.RatingLow.setMaximum(10.0)
        self.RatingLow.setObjectName("RatingLow")
        self.RatingMidLabel = QtWidgets.QLabel(SearchSettingDialog)
        self.RatingMidLabel.setGeometry(QtCore.QRect(210, 80, 20, 30))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(12)
        self.RatingMidLabel.setFont(font)
        self.RatingMidLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.RatingMidLabel.setTextFormat(QtCore.Qt.AutoText)
        self.RatingMidLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.RatingMidLabel.setObjectName("RatingMidLabel")
        self.RatingHigh = QtWidgets.QDoubleSpinBox(SearchSettingDialog)
        self.RatingHigh.setGeometry(QtCore.QRect(240, 80, 100, 30))
        self.RatingHigh.setDecimals(1)
        self.RatingHigh.setMaximum(10.0)
        self.RatingHigh.setProperty("value", 10.0)
        self.RatingHigh.setObjectName("RatingHigh")
        self.DateLabel = QtWidgets.QLabel(SearchSettingDialog)
        self.DateLabel.setGeometry(QtCore.QRect(20, 130, 70, 30))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(12)
        self.DateLabel.setFont(font)
        self.DateLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.DateLabel.setTextFormat(QtCore.Qt.AutoText)
        self.DateLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.DateLabel.setObjectName("DateLabel")
        self.DateMidLabel = QtWidgets.QLabel(SearchSettingDialog)
        self.DateMidLabel.setGeometry(QtCore.QRect(210, 130, 20, 30))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(12)
        self.DateMidLabel.setFont(font)
        self.DateMidLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.DateMidLabel.setTextFormat(QtCore.Qt.AutoText)
        self.DateMidLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.DateMidLabel.setObjectName("DateMidLabel")
        self.DateLow = QtWidgets.QDateEdit(SearchSettingDialog)
        self.DateLow.setGeometry(QtCore.QRect(100, 130, 100, 30))
        self.DateLow.setDateTime(QtCore.QDateTime(QtCore.QDate(1900, 1, 1), QtCore.QTime(0, 0, 0)))
        self.DateLow.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(1900, 1, 1), QtCore.QTime(0, 0, 0)))
        self.DateLow.setMaximumDate(QtCore.QDate(2025, 12, 31))
        self.DateLow.setCalendarPopup(True)
        self.DateLow.setObjectName("DateLow")
        self.GenreLabel = QtWidgets.QLabel(SearchSettingDialog)
        self.GenreLabel.setGeometry(QtCore.QRect(20, 180, 40, 30))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(12)
        self.GenreLabel.setFont(font)
        self.GenreLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.GenreLabel.setTextFormat(QtCore.Qt.AutoText)
        self.GenreLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.GenreLabel.setObjectName("GenreLabel")
        self.Genre = QtWidgets.QComboBox(SearchSettingDialog)
        self.Genre.setGeometry(QtCore.QRect(70, 180, 100, 30))
        self.Genre.setObjectName("Genre")
        self.DateHigh = QtWidgets.QDateEdit(SearchSettingDialog)
        self.DateHigh.setGeometry(QtCore.QRect(240, 130, 100, 30))
        self.DateHigh.setDateTime(QtCore.QDateTime(QtCore.QDate(2025, 12, 31), QtCore.QTime(0, 0, 0)))
        self.DateHigh.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(1900, 1, 1), QtCore.QTime(0, 0, 0)))
        self.DateHigh.setMaximumDate(QtCore.QDate(2025, 12, 31))
        self.DateHigh.setMinimumDate(QtCore.QDate(1900, 1, 1))
        self.DateHigh.setCalendarPopup(True)
        self.DateHigh.setObjectName("DateHigh")
        self.Cancel = QtWidgets.QPushButton(SearchSettingDialog)
        self.Cancel.setGeometry(QtCore.QRect(270, 180, 70, 30))
        font = QtGui.QFont()
        font.setFamily("宋体")
        self.Cancel.setFont(font)
        self.Cancel.setObjectName("Cancel")
        self.Confirm = QtWidgets.QPushButton(SearchSettingDialog)
        self.Confirm.setGeometry(QtCore.QRect(190, 180, 70, 30))
        font = QtGui.QFont()
        font.setFamily("宋体")
        self.Confirm.setFont(font)
        self.Confirm.setDefault(True)
        self.Confirm.setObjectName("Confirm")
        self.RatingLabel.setBuddy(self.RatingLow)
        self.RatingMidLabel.setBuddy(self.RatingHigh)
        self.DateLabel.setBuddy(self.DateLow)
        self.DateMidLabel.setBuddy(self.DateHigh)
        self.GenreLabel.setBuddy(self.Genre)

        self.retranslateUi(SearchSettingDialog)
        self.Cancel.clicked.connect(SearchSettingDialog.reject)
        self.Confirm.clicked.connect(SearchSettingDialog.setSearch)
        QtCore.QMetaObject.connectSlotsByName(SearchSettingDialog)
        SearchSettingDialog.setTabOrder(self.RatingLow, self.RatingHigh)
        SearchSettingDialog.setTabOrder(self.RatingHigh, self.DateLow)
        SearchSettingDialog.setTabOrder(self.DateLow, self.DateHigh)
        SearchSettingDialog.setTabOrder(self.DateHigh, self.Genre)
        SearchSettingDialog.setTabOrder(self.Genre, self.Confirm)
        SearchSettingDialog.setTabOrder(self.Confirm, self.Cancel)

    def retranslateUi(self, SearchSettingDialog):
        _translate = QtCore.QCoreApplication.translate
        SearchSettingDialog.setWindowTitle(_translate("SearchSettingDialog", "搜索条件设置"))
        self.RatingLabel.setText(_translate("SearchSettingDialog", "电影评分"))
        self.Title.setText(_translate("SearchSettingDialog", "搜索条件设置"))
        self.RatingMidLabel.setText(_translate("SearchSettingDialog", "到"))
        self.DateLabel.setText(_translate("SearchSettingDialog", "上映时间"))
        self.DateMidLabel.setText(_translate("SearchSettingDialog", "到"))
        self.GenreLabel.setText(_translate("SearchSettingDialog", "分类"))
        self.Cancel.setText(_translate("SearchSettingDialog", "取消"))
        self.Confirm.setText(_translate("SearchSettingDialog", "确认"))
