# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\DBProj\GUI\SubInfoDialogUI.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SubInfoDialog(object):
    def setupUi(self, SubInfoDialog):
        SubInfoDialog.setObjectName("SubInfoDialog")
        SubInfoDialog.resize(600, 400)
        self.MainTabs = QtWidgets.QTabWidget(SubInfoDialog)
        self.MainTabs.setGeometry(QtCore.QRect(0, 80, 600, 320))
        self.MainTabs.setObjectName("MainTabs")
        self.CompanyTab = QtWidgets.QWidget()
        self.CompanyTab.setObjectName("CompanyTab")
        self.CompanySearchText = QtWidgets.QLineEdit(self.CompanyTab)
        self.CompanySearchText.setGeometry(QtCore.QRect(20, 50, 220, 30))
        self.CompanySearchText.setObjectName("CompanySearchText")
        self.CompanySearchResult = QtWidgets.QTableWidget(self.CompanyTab)
        self.CompanySearchResult.setGeometry(QtCore.QRect(20, 100, 220, 180))
        self.CompanySearchResult.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.CompanySearchResult.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.CompanySearchResult.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.CompanySearchResult.setObjectName("CompanySearchResult")
        self.CompanySearchResult.setColumnCount(2)
        self.CompanySearchResult.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.CompanySearchResult.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.CompanySearchResult.setHorizontalHeaderItem(1, item)
        self.CompanySearchResult.horizontalHeader().setStretchLastSection(True)
        self.CompanySearchResult.verticalHeader().setVisible(False)
        self.CompanySearchLabel = QtWidgets.QLabel(self.CompanyTab)
        self.CompanySearchLabel.setGeometry(QtCore.QRect(20, 20, 220, 30))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(12)
        self.CompanySearchLabel.setFont(font)
        self.CompanySearchLabel.setObjectName("CompanySearchLabel")
        self.CompanyName = QtWidgets.QLineEdit(self.CompanyTab)
        self.CompanyName.setGeometry(QtCore.QRect(360, 100, 220, 30))
        self.CompanyName.setObjectName("CompanyName")
        self.CompanyNameLabel = QtWidgets.QLabel(self.CompanyTab)
        self.CompanyNameLabel.setGeometry(QtCore.QRect(280, 100, 70, 30))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(12)
        self.CompanyNameLabel.setFont(font)
        self.CompanyNameLabel.setObjectName("CompanyNameLabel")
        self.CompanyNationality = QtWidgets.QLineEdit(self.CompanyTab)
        self.CompanyNationality.setGeometry(QtCore.QRect(360, 150, 220, 30))
        self.CompanyNationality.setObjectName("CompanyNationality")
        self.CompanyNationalityLabel = QtWidgets.QLabel(self.CompanyTab)
        self.CompanyNationalityLabel.setGeometry(QtCore.QRect(280, 150, 70, 30))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(12)
        self.CompanyNationalityLabel.setFont(font)
        self.CompanyNationalityLabel.setObjectName("CompanyNationalityLabel")
        self.CompanyTitle = QtWidgets.QLabel(self.CompanyTab)
        self.CompanyTitle.setGeometry(QtCore.QRect(280, 30, 300, 30))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.CompanyTitle.setFont(font)
        self.CompanyTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.CompanyTitle.setObjectName("CompanyTitle")
        self.CompanyAddButton = QtWidgets.QPushButton(self.CompanyTab)
        self.CompanyAddButton.setGeometry(QtCore.QRect(280, 210, 140, 30))
        self.CompanyAddButton.setDefault(True)
        self.CompanyAddButton.setObjectName("CompanyAddButton")
        self.CompanyModifyButton = QtWidgets.QPushButton(self.CompanyTab)
        self.CompanyModifyButton.setGeometry(QtCore.QRect(440, 210, 140, 30))
        self.CompanyModifyButton.setDefault(True)
        self.CompanyModifyButton.setObjectName("CompanyModifyButton")
        self.CompanyDeleteButton = QtWidgets.QPushButton(self.CompanyTab)
        self.CompanyDeleteButton.setGeometry(QtCore.QRect(280, 250, 300, 30))
        self.CompanyDeleteButton.setDefault(True)
        self.CompanyDeleteButton.setObjectName("CompanyDeleteButton")
        self.MainTabs.addTab(self.CompanyTab, "")
        self.GenreTab = QtWidgets.QWidget()
        self.GenreTab.setObjectName("GenreTab")
        self.GenreModifyButton = QtWidgets.QPushButton(self.GenreTab)
        self.GenreModifyButton.setGeometry(QtCore.QRect(440, 210, 140, 30))
        self.GenreModifyButton.setDefault(True)
        self.GenreModifyButton.setObjectName("GenreModifyButton")
        self.GenreDeleteButton = QtWidgets.QPushButton(self.GenreTab)
        self.GenreDeleteButton.setGeometry(QtCore.QRect(280, 250, 300, 30))
        self.GenreDeleteButton.setDefault(True)
        self.GenreDeleteButton.setObjectName("GenreDeleteButton")
        self.GenreAddButton = QtWidgets.QPushButton(self.GenreTab)
        self.GenreAddButton.setGeometry(QtCore.QRect(280, 210, 140, 30))
        self.GenreAddButton.setDefault(True)
        self.GenreAddButton.setObjectName("GenreAddButton")
        self.GenreSearchResult = QtWidgets.QTableWidget(self.GenreTab)
        self.GenreSearchResult.setGeometry(QtCore.QRect(20, 100, 220, 180))
        self.GenreSearchResult.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.GenreSearchResult.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.GenreSearchResult.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.GenreSearchResult.setObjectName("GenreSearchResult")
        self.GenreSearchResult.setColumnCount(1)
        self.GenreSearchResult.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.GenreSearchResult.setHorizontalHeaderItem(0, item)
        self.GenreSearchResult.horizontalHeader().setStretchLastSection(True)
        self.GenreSearchResult.verticalHeader().setVisible(False)
        self.GenreSearchLabel = QtWidgets.QLabel(self.GenreTab)
        self.GenreSearchLabel.setGeometry(QtCore.QRect(20, 20, 220, 30))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(12)
        self.GenreSearchLabel.setFont(font)
        self.GenreSearchLabel.setObjectName("GenreSearchLabel")
        self.GenreSearchText = QtWidgets.QLineEdit(self.GenreTab)
        self.GenreSearchText.setGeometry(QtCore.QRect(20, 50, 220, 30))
        self.GenreSearchText.setObjectName("GenreSearchText")
        self.GenreName = QtWidgets.QLineEdit(self.GenreTab)
        self.GenreName.setGeometry(QtCore.QRect(360, 120, 220, 30))
        self.GenreName.setObjectName("GenreName")
        self.GenreTitle = QtWidgets.QLabel(self.GenreTab)
        self.GenreTitle.setGeometry(QtCore.QRect(280, 30, 300, 30))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.GenreTitle.setFont(font)
        self.GenreTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.GenreTitle.setObjectName("GenreTitle")
        self.GenreNameLabel = QtWidgets.QLabel(self.GenreTab)
        self.GenreNameLabel.setGeometry(QtCore.QRect(280, 120, 70, 30))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(12)
        self.GenreNameLabel.setFont(font)
        self.GenreNameLabel.setObjectName("GenreNameLabel")
        self.MainTabs.addTab(self.GenreTab, "")
        self.DirectorTab = QtWidgets.QWidget()
        self.DirectorTab.setObjectName("DirectorTab")
        self.DirectorModifyButton = QtWidgets.QPushButton(self.DirectorTab)
        self.DirectorModifyButton.setGeometry(QtCore.QRect(440, 210, 140, 30))
        self.DirectorModifyButton.setDefault(True)
        self.DirectorModifyButton.setObjectName("DirectorModifyButton")
        self.DirectorDeleteButton = QtWidgets.QPushButton(self.DirectorTab)
        self.DirectorDeleteButton.setGeometry(QtCore.QRect(280, 250, 300, 30))
        self.DirectorDeleteButton.setDefault(True)
        self.DirectorDeleteButton.setObjectName("DirectorDeleteButton")
        self.DirectorAddButton = QtWidgets.QPushButton(self.DirectorTab)
        self.DirectorAddButton.setGeometry(QtCore.QRect(280, 210, 140, 30))
        self.DirectorAddButton.setDefault(True)
        self.DirectorAddButton.setObjectName("DirectorAddButton")
        self.DirectorSearchResult = QtWidgets.QTableWidget(self.DirectorTab)
        self.DirectorSearchResult.setGeometry(QtCore.QRect(20, 100, 220, 180))
        self.DirectorSearchResult.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.DirectorSearchResult.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.DirectorSearchResult.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.DirectorSearchResult.setObjectName("DirectorSearchResult")
        self.DirectorSearchResult.setColumnCount(2)
        self.DirectorSearchResult.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.DirectorSearchResult.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.DirectorSearchResult.setHorizontalHeaderItem(1, item)
        self.DirectorSearchResult.horizontalHeader().setStretchLastSection(True)
        self.DirectorSearchResult.verticalHeader().setVisible(False)
        self.DirectorSearchLabel = QtWidgets.QLabel(self.DirectorTab)
        self.DirectorSearchLabel.setGeometry(QtCore.QRect(20, 20, 220, 30))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(12)
        self.DirectorSearchLabel.setFont(font)
        self.DirectorSearchLabel.setObjectName("DirectorSearchLabel")
        self.DirectorSearchText = QtWidgets.QLineEdit(self.DirectorTab)
        self.DirectorSearchText.setGeometry(QtCore.QRect(20, 50, 220, 30))
        self.DirectorSearchText.setObjectName("DirectorSearchText")
        self.DirectorAvatarLabel = QtWidgets.QLabel(self.DirectorTab)
        self.DirectorAvatarLabel.setGeometry(QtCore.QRect(280, 120, 70, 30))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(12)
        self.DirectorAvatarLabel.setFont(font)
        self.DirectorAvatarLabel.setObjectName("DirectorAvatarLabel")
        self.DirectorName = QtWidgets.QLineEdit(self.DirectorTab)
        self.DirectorName.setGeometry(QtCore.QRect(360, 80, 220, 30))
        self.DirectorName.setObjectName("DirectorName")
        self.DirectorTitle = QtWidgets.QLabel(self.DirectorTab)
        self.DirectorTitle.setGeometry(QtCore.QRect(280, 30, 300, 30))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.DirectorTitle.setFont(font)
        self.DirectorTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.DirectorTitle.setObjectName("DirectorTitle")
        self.DirectorAvatar = QtWidgets.QLineEdit(self.DirectorTab)
        self.DirectorAvatar.setGeometry(QtCore.QRect(360, 120, 220, 30))
        self.DirectorAvatar.setObjectName("DirectorAvatar")
        self.DirectorNameLabel = QtWidgets.QLabel(self.DirectorTab)
        self.DirectorNameLabel.setGeometry(QtCore.QRect(280, 80, 70, 30))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(12)
        self.DirectorNameLabel.setFont(font)
        self.DirectorNameLabel.setObjectName("DirectorNameLabel")
        self.DirectorAltLabel = QtWidgets.QLabel(self.DirectorTab)
        self.DirectorAltLabel.setGeometry(QtCore.QRect(280, 160, 70, 30))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(12)
        self.DirectorAltLabel.setFont(font)
        self.DirectorAltLabel.setObjectName("DirectorAltLabel")
        self.DirectorAlt = QtWidgets.QLineEdit(self.DirectorTab)
        self.DirectorAlt.setGeometry(QtCore.QRect(360, 160, 220, 30))
        self.DirectorAlt.setObjectName("DirectorAlt")
        self.MainTabs.addTab(self.DirectorTab, "")
        self.CastTab = QtWidgets.QWidget()
        self.CastTab.setObjectName("CastTab")
        self.CastModifyButton = QtWidgets.QPushButton(self.CastTab)
        self.CastModifyButton.setGeometry(QtCore.QRect(440, 210, 140, 30))
        self.CastModifyButton.setDefault(True)
        self.CastModifyButton.setObjectName("CastModifyButton")
        self.CastDeleteButton = QtWidgets.QPushButton(self.CastTab)
        self.CastDeleteButton.setGeometry(QtCore.QRect(280, 250, 300, 30))
        self.CastDeleteButton.setDefault(True)
        self.CastDeleteButton.setObjectName("CastDeleteButton")
        self.CastAddButton = QtWidgets.QPushButton(self.CastTab)
        self.CastAddButton.setGeometry(QtCore.QRect(280, 210, 140, 30))
        self.CastAddButton.setDefault(True)
        self.CastAddButton.setObjectName("CastAddButton")
        self.CastSearchResult = QtWidgets.QTableWidget(self.CastTab)
        self.CastSearchResult.setGeometry(QtCore.QRect(20, 100, 220, 180))
        self.CastSearchResult.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.CastSearchResult.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.CastSearchResult.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.CastSearchResult.setObjectName("CastSearchResult")
        self.CastSearchResult.setColumnCount(2)
        self.CastSearchResult.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.CastSearchResult.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.CastSearchResult.setHorizontalHeaderItem(1, item)
        self.CastSearchResult.horizontalHeader().setStretchLastSection(True)
        self.CastSearchResult.verticalHeader().setVisible(False)
        self.CastSearchLabel = QtWidgets.QLabel(self.CastTab)
        self.CastSearchLabel.setGeometry(QtCore.QRect(20, 20, 220, 30))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(12)
        self.CastSearchLabel.setFont(font)
        self.CastSearchLabel.setObjectName("CastSearchLabel")
        self.CastSearchText = QtWidgets.QLineEdit(self.CastTab)
        self.CastSearchText.setGeometry(QtCore.QRect(20, 50, 220, 30))
        self.CastSearchText.setObjectName("CastSearchText")
        self.CastAvatarLabel = QtWidgets.QLabel(self.CastTab)
        self.CastAvatarLabel.setGeometry(QtCore.QRect(280, 120, 70, 30))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(12)
        self.CastAvatarLabel.setFont(font)
        self.CastAvatarLabel.setObjectName("CastAvatarLabel")
        self.CastAvatar = QtWidgets.QLineEdit(self.CastTab)
        self.CastAvatar.setGeometry(QtCore.QRect(360, 120, 220, 30))
        self.CastAvatar.setObjectName("CastAvatar")
        self.CastAlt = QtWidgets.QLineEdit(self.CastTab)
        self.CastAlt.setGeometry(QtCore.QRect(360, 160, 220, 30))
        self.CastAlt.setObjectName("CastAlt")
        self.CastTitle = QtWidgets.QLabel(self.CastTab)
        self.CastTitle.setGeometry(QtCore.QRect(280, 30, 300, 30))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.CastTitle.setFont(font)
        self.CastTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.CastTitle.setObjectName("CastTitle")
        self.CastNameLabel = QtWidgets.QLabel(self.CastTab)
        self.CastNameLabel.setGeometry(QtCore.QRect(280, 80, 70, 30))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(12)
        self.CastNameLabel.setFont(font)
        self.CastNameLabel.setObjectName("CastNameLabel")
        self.CastName = QtWidgets.QLineEdit(self.CastTab)
        self.CastName.setGeometry(QtCore.QRect(360, 80, 220, 30))
        self.CastName.setObjectName("CastName")
        self.CastAltLabel = QtWidgets.QLabel(self.CastTab)
        self.CastAltLabel.setGeometry(QtCore.QRect(280, 160, 70, 30))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(12)
        self.CastAltLabel.setFont(font)
        self.CastAltLabel.setObjectName("CastAltLabel")
        self.MainTabs.addTab(self.CastTab, "")
        self.Title = QtWidgets.QLabel(SubInfoDialog)
        self.Title.setGeometry(QtCore.QRect(20, 20, 160, 30))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.Title.setFont(font)
        self.Title.setAlignment(QtCore.Qt.AlignCenter)
        self.Title.setObjectName("Title")
        self.OKButton = QtWidgets.QPushButton(SubInfoDialog)
        self.OKButton.setGeometry(QtCore.QRect(490, 20, 90, 30))
        self.OKButton.setDefault(True)
        self.OKButton.setObjectName("OKButton")
        self.CompanySearchLabel.setBuddy(self.CompanySearchText)
        self.CompanyNameLabel.setBuddy(self.CompanyName)
        self.CompanyNationalityLabel.setBuddy(self.CompanyNationality)
        self.GenreSearchLabel.setBuddy(self.GenreSearchText)
        self.GenreNameLabel.setBuddy(self.GenreName)
        self.DirectorSearchLabel.setBuddy(self.DirectorSearchText)
        self.DirectorAvatarLabel.setBuddy(self.DirectorAvatar)
        self.DirectorNameLabel.setBuddy(self.DirectorName)
        self.DirectorAltLabel.setBuddy(self.DirectorAlt)
        self.CastSearchLabel.setBuddy(self.CastSearchText)
        self.CastAvatarLabel.setBuddy(self.CastAvatar)
        self.CastNameLabel.setBuddy(self.CastName)
        self.CastAltLabel.setBuddy(self.CastAlt)

        self.retranslateUi(SubInfoDialog)
        self.OKButton.clicked.connect(SubInfoDialog.accept)
        self.CompanySearchText.textChanged['QString'].connect(SubInfoDialog.searchCompany)
        self.CompanySearchResult.cellDoubleClicked['int','int'].connect(SubInfoDialog.loadCompany)
        self.CompanyAddButton.clicked.connect(SubInfoDialog.addCompany)
        self.CompanyModifyButton.clicked.connect(SubInfoDialog.modifyCompany)
        self.CompanyDeleteButton.clicked.connect(SubInfoDialog.deleteCompany)
        self.GenreSearchText.textChanged['QString'].connect(SubInfoDialog.searchGenre)
        self.GenreSearchResult.cellDoubleClicked['int','int'].connect(SubInfoDialog.loadGenre)
        self.GenreAddButton.clicked.connect(SubInfoDialog.addGenre)
        self.GenreModifyButton.clicked.connect(SubInfoDialog.modifyGenre)
        self.GenreDeleteButton.clicked.connect(SubInfoDialog.deleteGenre)
        self.DirectorSearchText.textChanged['QString'].connect(SubInfoDialog.searchDirector)
        self.DirectorSearchResult.cellDoubleClicked['int','int'].connect(SubInfoDialog.loadDirector)
        self.DirectorAddButton.clicked.connect(SubInfoDialog.addDirector)
        self.DirectorModifyButton.clicked.connect(SubInfoDialog.modifyDirector)
        self.DirectorDeleteButton.clicked.connect(SubInfoDialog.deleteDirector)
        self.CastSearchText.textChanged['QString'].connect(SubInfoDialog.searchCast)
        self.CastSearchResult.cellDoubleClicked['int','int'].connect(SubInfoDialog.loadCast)
        self.CastAddButton.clicked.connect(SubInfoDialog.addCast)
        self.CastModifyButton.clicked.connect(SubInfoDialog.modifyCast)
        self.CastDeleteButton.clicked.connect(SubInfoDialog.deleteCast)
        QtCore.QMetaObject.connectSlotsByName(SubInfoDialog)
        SubInfoDialog.setTabOrder(self.OKButton, self.MainTabs)
        SubInfoDialog.setTabOrder(self.MainTabs, self.CompanySearchText)
        SubInfoDialog.setTabOrder(self.CompanySearchText, self.CompanySearchResult)
        SubInfoDialog.setTabOrder(self.CompanySearchResult, self.CompanyName)
        SubInfoDialog.setTabOrder(self.CompanyName, self.CompanyNationality)
        SubInfoDialog.setTabOrder(self.CompanyNationality, self.CompanyAddButton)
        SubInfoDialog.setTabOrder(self.CompanyAddButton, self.CompanyModifyButton)
        SubInfoDialog.setTabOrder(self.CompanyModifyButton, self.CompanyDeleteButton)
        SubInfoDialog.setTabOrder(self.CompanyDeleteButton, self.GenreSearchText)
        SubInfoDialog.setTabOrder(self.GenreSearchText, self.GenreSearchResult)
        SubInfoDialog.setTabOrder(self.GenreSearchResult, self.GenreName)
        SubInfoDialog.setTabOrder(self.GenreName, self.GenreAddButton)
        SubInfoDialog.setTabOrder(self.GenreAddButton, self.GenreModifyButton)
        SubInfoDialog.setTabOrder(self.GenreModifyButton, self.GenreDeleteButton)
        SubInfoDialog.setTabOrder(self.GenreDeleteButton, self.DirectorSearchText)
        SubInfoDialog.setTabOrder(self.DirectorSearchText, self.DirectorSearchResult)
        SubInfoDialog.setTabOrder(self.DirectorSearchResult, self.DirectorName)
        SubInfoDialog.setTabOrder(self.DirectorName, self.DirectorAvatar)
        SubInfoDialog.setTabOrder(self.DirectorAvatar, self.DirectorAlt)
        SubInfoDialog.setTabOrder(self.DirectorAlt, self.DirectorAddButton)
        SubInfoDialog.setTabOrder(self.DirectorAddButton, self.DirectorModifyButton)
        SubInfoDialog.setTabOrder(self.DirectorModifyButton, self.DirectorDeleteButton)
        SubInfoDialog.setTabOrder(self.DirectorDeleteButton, self.CastSearchText)
        SubInfoDialog.setTabOrder(self.CastSearchText, self.CastSearchResult)
        SubInfoDialog.setTabOrder(self.CastSearchResult, self.CastName)
        SubInfoDialog.setTabOrder(self.CastName, self.CastAvatar)
        SubInfoDialog.setTabOrder(self.CastAvatar, self.CastAlt)
        SubInfoDialog.setTabOrder(self.CastAlt, self.CastAddButton)
        SubInfoDialog.setTabOrder(self.CastAddButton, self.CastModifyButton)
        SubInfoDialog.setTabOrder(self.CastModifyButton, self.CastDeleteButton)

    def retranslateUi(self, SubInfoDialog):
        _translate = QtCore.QCoreApplication.translate
        SubInfoDialog.setWindowTitle(_translate("SubInfoDialog", "附属信息管理"))
        self.CompanySearchText.setPlaceholderText(_translate("SubInfoDialog", "请输入公司名称"))
        item = self.CompanySearchResult.horizontalHeaderItem(0)
        item.setText(_translate("SubInfoDialog", "公司名称"))
        item = self.CompanySearchResult.horizontalHeaderItem(1)
        item.setText(_translate("SubInfoDialog", "国家/地区"))
        self.CompanySearchLabel.setText(_translate("SubInfoDialog", "搜索公司名称："))
        self.CompanyName.setPlaceholderText(_translate("SubInfoDialog", "请输入公司名称"))
        self.CompanyNameLabel.setText(_translate("SubInfoDialog", "公司名称"))
        self.CompanyNationality.setPlaceholderText(_translate("SubInfoDialog", "请输入公司国家/地区"))
        self.CompanyNationalityLabel.setText(_translate("SubInfoDialog", "国家/地区"))
        self.CompanyTitle.setText(_translate("SubInfoDialog", "公司信息"))
        self.CompanyAddButton.setText(_translate("SubInfoDialog", "添加"))
        self.CompanyModifyButton.setText(_translate("SubInfoDialog", "修改"))
        self.CompanyDeleteButton.setText(_translate("SubInfoDialog", "删除"))
        self.MainTabs.setTabText(self.MainTabs.indexOf(self.CompanyTab), _translate("SubInfoDialog", "公司信息"))
        self.GenreModifyButton.setText(_translate("SubInfoDialog", "修改"))
        self.GenreDeleteButton.setText(_translate("SubInfoDialog", "删除"))
        self.GenreAddButton.setText(_translate("SubInfoDialog", "添加"))
        item = self.GenreSearchResult.horizontalHeaderItem(0)
        item.setText(_translate("SubInfoDialog", "分类"))
        self.GenreSearchLabel.setText(_translate("SubInfoDialog", "搜索分类："))
        self.GenreSearchText.setPlaceholderText(_translate("SubInfoDialog", "请输入分类名称"))
        self.GenreName.setPlaceholderText(_translate("SubInfoDialog", "请输入分类名称"))
        self.GenreTitle.setText(_translate("SubInfoDialog", "分类信息"))
        self.GenreNameLabel.setText(_translate("SubInfoDialog", "分类名称"))
        self.MainTabs.setTabText(self.MainTabs.indexOf(self.GenreTab), _translate("SubInfoDialog", "分类信息"))
        self.DirectorModifyButton.setText(_translate("SubInfoDialog", "修改"))
        self.DirectorDeleteButton.setText(_translate("SubInfoDialog", "删除"))
        self.DirectorAddButton.setText(_translate("SubInfoDialog", "添加"))
        item = self.DirectorSearchResult.horizontalHeaderItem(0)
        item.setText(_translate("SubInfoDialog", "导演姓名"))
        item = self.DirectorSearchResult.horizontalHeaderItem(1)
        item.setText(_translate("SubInfoDialog", "豆瓣链接"))
        self.DirectorSearchLabel.setText(_translate("SubInfoDialog", "搜索导演姓名："))
        self.DirectorSearchText.setPlaceholderText(_translate("SubInfoDialog", "请输入导演姓名"))
        self.DirectorAvatarLabel.setText(_translate("SubInfoDialog", "海报链接"))
        self.DirectorName.setPlaceholderText(_translate("SubInfoDialog", "请输入导演名称"))
        self.DirectorTitle.setText(_translate("SubInfoDialog", "导演信息"))
        self.DirectorAvatar.setPlaceholderText(_translate("SubInfoDialog", "请输入导演海报链接"))
        self.DirectorNameLabel.setText(_translate("SubInfoDialog", "导演名称"))
        self.DirectorAltLabel.setText(_translate("SubInfoDialog", "豆瓣链接"))
        self.DirectorAlt.setPlaceholderText(_translate("SubInfoDialog", "请输入导演豆瓣链接"))
        self.MainTabs.setTabText(self.MainTabs.indexOf(self.DirectorTab), _translate("SubInfoDialog", "导演信息"))
        self.CastModifyButton.setText(_translate("SubInfoDialog", "修改"))
        self.CastDeleteButton.setText(_translate("SubInfoDialog", "删除"))
        self.CastAddButton.setText(_translate("SubInfoDialog", "添加"))
        item = self.CastSearchResult.horizontalHeaderItem(0)
        item.setText(_translate("SubInfoDialog", "演员姓名"))
        item = self.CastSearchResult.horizontalHeaderItem(1)
        item.setText(_translate("SubInfoDialog", "豆瓣链接"))
        self.CastSearchLabel.setText(_translate("SubInfoDialog", "搜索演员姓名："))
        self.CastSearchText.setPlaceholderText(_translate("SubInfoDialog", "请输入演员姓名"))
        self.CastAvatarLabel.setText(_translate("SubInfoDialog", "海报链接"))
        self.CastAvatar.setPlaceholderText(_translate("SubInfoDialog", "请输入演员海报链接"))
        self.CastAlt.setPlaceholderText(_translate("SubInfoDialog", "请输入演员豆瓣链接"))
        self.CastTitle.setText(_translate("SubInfoDialog", "演员信息"))
        self.CastNameLabel.setText(_translate("SubInfoDialog", "演员名称"))
        self.CastName.setPlaceholderText(_translate("SubInfoDialog", "请输入演员名称"))
        self.CastAltLabel.setText(_translate("SubInfoDialog", "豆瓣链接"))
        self.MainTabs.setTabText(self.MainTabs.indexOf(self.CastTab), _translate("SubInfoDialog", "演员信息"))
        self.Title.setText(_translate("SubInfoDialog", "附属信息管理"))
        self.OKButton.setText(_translate("SubInfoDialog", "返回"))
